export const BUDGET_WEEKS = [
  {
    num: 1, title: 'Semaine 1 – Les bases du placard intelligent', color: 'from-lime-100 to-green-100',
    objective: 'Constituer un placard de base économique et nutritif',
    habits: ['Acheter les secs en grande quantité : riz, lentilles, avoine', 'Comparer les prix aux 100g (pas au produit)', 'Bannir les produits ultra-transformés qui coûtent cher et nourrissent peu'],
    nutrition: 'Légumineuses + céréales = protéines complètes économiques',
    nutritionDetail: ['Lentilles sèches (1kg ~1.50€) = 10 portions de protéines', 'Riz complet (1kg ~1.50€) = 8-10 portions', 'Flocons d\'avoine (1kg ~1.80€) = 20 petits-déjeuners', 'Œufs (12 ~2.20€) = 12 portions de protéines complètes'],
    mealExample: 'Riz + lentilles + oignon caramélisé + huile olive = repas complet pour 0.50€',
    activity: 'Marche ou vélo pour les courses (économise carburant + fait du sport)',
    activityDetail: ['Les courses à pied ou vélo = transport + sport', 'Marché de fin de journée : invendus bradés -40 à -60%', 'Courses en ligne avec promo du jour : évite les achats impulsifs'],
    checklist: ['Placard de base constitué', 'Prix aux 100g maîtrisé', 'Légumineuses + céréales', 'Zéro ultra-transformé'],
    tip: 'Le calcul simple : 1kg de lentilles sèches = 10 repas protéinés pour 1.50€ = 0.15€/repas protéiné. La viande : 0.80-2€/repas. Faites le calcul.',
  },
  {
    num: 2, title: 'Semaine 2 – Zéro gaspillage', color: 'from-green-100 to-teal-100',
    objective: 'Réduire de 50% le gaspillage alimentaire = économiser 20-30€/mois',
    habits: ['FIFO en cuisine : First In First Out (vieux devant, nouveau derrière)', 'Congeler avant que ça soit périmé', 'Les restes = base du repas suivant'],
    nutrition: 'Cuisiner les restes intelligemment',
    nutritionDetail: ['Pain dur → pain perdu, bruschetta, chapelure maison', 'Légumes qui fléchissent → soupe, sauce tomate, ratatouille', 'Riz cuit → riz frit, arancini, galettes', 'Viande restante → hachée en bolognaise, en wrap'],
    mealExample: 'Frittata du vendredi soir = omelette avec TOUS les restes de légumes de la semaine',
    activity: 'Jardinage et potager anti-gaspi',
    activityDetail: ['Les herbes en pot évitent d\'acheter des bouquets jetés aux 3/4', 'Tomates, courgettes : facile à cultiver, économies de 20-30€/été', 'Les fanes de carottes, feuilles de radis : comestibles et nutritives'],
    checklist: ['FIFO organisé', 'Congélateur utilisé', 'Restes cuisinés', 'Potager débuté'],
    tip: 'Les Français jettent en moyenne 30kg d\'aliments par an et par personne = 100-150€ gaspillés. Le congélateur est votre meilleur ami.',
  },
  {
    num: 3, title: 'Semaine 3 – Les protéines économiques', color: 'from-teal-100 to-cyan-100',
    objective: 'Manger suffisamment de protéines sous les 2€/repas',
    habits: ['Manger des légumineuses 4x cette semaine', 'Essayer 1 nouvelle légumineuse (haricots blancs, pois cassés)', 'Réduire la viande à 2-3 fois par semaine maximum'],
    nutrition: 'Protéines végétales et animales économiques',
    nutritionDetail: ['Classement prix pour 20g de protéines : lentilles 0.15€ < œufs 0.35€ < sardines 0.60€ < poulet 1.20€ < viande rouge 2.50-4€', 'Abats (foie, cœur) : 3-5x moins chers que muscle, plus nutritifs', 'Poissons en conserve : sardines, maquereau, thon = riches et économiques'],
    mealExample: 'Dal de pois cassés + riz basmati + oignon frit = repas indien pour 0.40€/portion',
    activity: 'Sport gratuit en plein air',
    activityDetail: ['Course à pied dans un parc = 0€', 'Calisthenics (musculation au poids de corps) = 0€', 'YouTube fitness : Hima, Fitness Blender, Thibault Geoffray = 0€'],
    checklist: ['Légumineuses 4x', 'Nouvelle légumineuse testée', 'Viande réduite', 'Sport gratuit'],
    tip: 'Le foie de bœuf coûte 3-4€/kg et contient plus de vitamine B12, fer, zinc et vitamine A que tout autre aliment. Nutritionnellement, c\'est le roi.',
  },
  {
    num: 4, title: 'Semaine 4 – Cuisiner malin, manger bien', color: 'from-cyan-100 to-blue-100',
    objective: 'Maîtriser les techniques pour maximiser goût et nutrition avec peu',
    habits: ['Cuisiner des plats en sauce mijotés (collagène, goût, économique)', 'Faire son pain ou ses crackers maison', 'Tester 1 recette internationale économique (dal, mujaddara, ribollita)'],
    nutrition: 'Cuisine mondiale économique = meilleure nutrition',
    nutritionDetail: ['La cuisine indienne, africaine, latine est basée sur les légumineuses = économique et nutritive', 'Les plats mijotés avec os donnent du bouillon : calcium, collagène, goût', 'Fermentation maison (yaourt, pain levain) : économise 60-70%'],
    mealExample: 'Mujaddara libanaise : riz + lentilles + oignons caramélisés = plat national complet pour 0.35€/portion',
    activity: 'Cuisine comme activité créative et sociale',
    activityDetail: ['Cuisiner debout 1h = 150 kcal dépensées', 'Inviter des amis pour cuisiner ensemble : économique et social', 'Marché bio de quartier : rencontres et économies combinées'],
    checklist: ['Plat mijoté cette semaine', 'Recette internationale testée', 'Fermentation maison', 'Budget ≤25€ atteint'],
    tip: 'La mujaddara libanaise (riz+lentilles+oignons caramélisés) est considérée comme un plat parfait nutritionnellement depuis 3000 ans. Coût : 0.35€/portion.',
  },
];

export const BUDGET_DAY = {
  label: 'Journée type petit budget',
  subtitle: 'Équilibrée et savoureuse pour <3€/jour',
  image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop',
  totalKcal: '2000 kcal',
  meals: [
    { icon: '🌅', name: 'Petit-déjeuner', time: '7h30', kcal: 380,
      items: ['Porridge avoine (40g) + eau ou lait', '1 banane ou pomme', 'Café ou thé', '1 c.à.s beurre de cacahuète (si disponible)'],
      alt: 'Pain complet grillé + œuf à la coque + fruit' },
    { icon: '🍽️', name: 'Déjeuner', time: '12h30', kcal: 600,
      items: ['Riz complet (150g cuit) ou pâtes complètes', 'Lentilles ou pois chiches assaisonnés (100g)', 'Légumes de saison cuits', 'Huile olive + épices'],
      alt: 'Soupe lentilles corail maison + pain complet' },
    { icon: '🍎', name: 'Collation', time: '16h00', kcal: 200,
      items: ['1 fruit de saison', '1 yaourt nature ou fromage blanc'],
      alt: 'Pain + beurre de cacahuète' },
    { icon: '🌙', name: 'Dîner', time: '19h30', kcal: 580,
      items: ['Omelette 2-3 œufs + légumes', 'ou Pâtes + sauce tomate maison + œuf poché', 'Pain complet', 'Fruit ou fromage blanc'],
      alt: 'Frittata de légumes + pain + salade' },
  ],
};

export const BUDGET_SHOPPING = [
  { cat: '🥩 Protéines économiques (budget: ~8€)', items: ['Œufs (12) ~2.20€', 'Lentilles vertes sèches (1kg) ~1.50€', 'Pois chiches secs (500g) ~1.20€', 'Sardines conserve x3 ~2.40€', 'Fromage blanc (1kg) ~2.50€'] },
  { cat: '🌾 Céréales (budget: ~6€)', items: ['Riz complet (1kg) ~1.50€', 'Flocons avoine (1kg) ~1.80€', 'Pâtes complètes (1kg) ~1.40€', 'Pain complet ~1.60€'] },
  { cat: '🥦 Légumes de saison (budget: ~7€)', items: ['Carottes (1kg) ~0.99€', 'Oignons (1kg) ~1.20€', 'Courgettes (1kg) ~1.80€', 'Épinards surgelés (1kg) ~2.20€', 'Tomates conserve x3 ~2.10€'] },
  { cat: '🍌 Fruits (budget: ~4€)', items: ['Bananes (1kg) ~1.50€', 'Pommes (1kg) ~2€', 'Compote pomme sans sucre x4 ~2€'] },
  { cat: '🛢️ Essentiels (budget: ~7€)', items: ['Huile colza (1L) ~2.50€', 'Beurre de cacahuète ~2.80€', 'Miel (pot) ~3€', 'Sel, poivre, épices de base ~2€'] },
];

export const BUDGET_SPORT = [
  { icon: '🏃', title: 'Course à pied en plein air',
    desc: '0€, 30 min 3x/semaine. L\'activité physique la plus accessible et la plus complète.',
    detail: { intro: 'La course à pied ne nécessite qu\'une paire de chaussures. C\'est l\'activité physique la plus accessible économiquement et l\'une des plus bénéfiques.',
      points: ['Débuter par le programme C25K (Couch to 5km) : gratuit, progressif', 'Parkrun : courses gratuites tous les samedis dans +200 villes', '30 min = 300-400 kcal, amélioration cardio, humeur, sommeil', 'Plein air = vitamine D en bonus'],
      example: 'Semaine 1 C25K : marche 1 min, course 30 sec, alternance 20 min. Progressif sur 9 semaines.',
      tip: 'Chaussures de course d\'occasion : Vinted, leboncoin. 10-30€ au lieu de 100-150€ neuves.' } },
  { icon: '💪', title: 'Calisthenics (poids de corps)',
    desc: 'Musculation sans matériel ni abonnement. Push-ups, squats, tractions = résultats prouvés.',
    detail: { intro: 'Le calisthenics est la musculation au poids de corps. Des athlètes de haut niveau ne s\'entraînent qu\'avec leur propre poids. Aucun frais, peut se faire n\'importe où.',
      points: ['Débutant : 3x10 push-ups, 3x15 squats, 3x10 fentes = séance complète', 'Barre de tractions (barre de porte, 20-30€) = le seul investissement utile', 'Application Freeletics ou YouTube "calisthenics débutant" = programmes gratuits', 'Progression en augmentant les répétitions ou la difficulté'],
      example: 'Programme "100 push-ups en 6 semaines" : gratuit en ligne, efficace, change la silhouette.',
      tip: 'Les parcs de street workout (barres fixes dans les parcs publics) sont gratuits et de plus en plus répandus.' } },
  { icon: '🚴', title: 'Vélo (transport + sport)',
    desc: 'Économise le transport et fait du sport simultanément. Double retour sur investissement.',
    detail: { intro: 'Le vélo comme moyen de transport principal est l\'investissement le plus rentable qui soit : on fait son activité physique sans y consacrer de temps supplémentaire.',
      points: ['Vélo d\'occasion : 50-150€ sur leboncoin vs vélo neuf 400-800€', 'Économies transport : 50-100€/mois de métro ou essence', 'Vélos en libre service (Vélib, etc.) : 30-40€/an illimité', '30 min vélo = cardio complet, 0€'],
      example: '4 km aller-retour travail en vélo = 30 min d\'exercice, 0€ de transport, épargne transport utilisée pour la nourriture.',
      tip: 'Antivol U : 20-30€. Lumières : 10€. Investissement total : 40€ rentabilisé en 1 mois de transport économisé.' } },
  { icon: '🎬', title: 'YouTube Fitness (0€)',
    desc: 'Hima, Fitness Blender, Thibault Geoffray : des centaines d\'heures de cours gratuits.',
    detail: { intro: 'YouTube offre un accès gratuit à des cours de sport de qualité professionnelle. Beaucoup de coachs renommés publient leur contenu gratuitement.',
      points: ['Fitness Blender (anglais) : 500+ vidéos de tous niveaux, HIIT, yoga, stretching', 'Thibault Geoffray (français) : musculation, nutrition, conseils', 'Yoga with Adriene (anglais) : yoga pour tous niveaux, gratuit', 'Hima (français) : dance fitness, cardio, accessible'],
      example: 'Défi : 30 jours de yoga Adriene gratuit. Transforme la souplesse, la posture et le bien-être mental.',
      tip: 'Pas de fibre internet ? Télécharger les vidéos en WiFi le soir pour les regarder offline le matin.' } },
];

export const BUDGET_DRINKS = [
  { icon: '💧', name: 'Eau du robinet', rec: '1.5-2L/jour', ok: true, detail: 'L\'eau du robinet française est contrôlée en permanence. Elle coûte 200-400x moins que l\'eau en bouteille. Investir dans une gourde (10-15€ d\'occasion) = rentabilisé en 1 semaine.' },
  { icon: '🍵', name: 'Thé vrac', rec: '2-3 tasses/jour', ok: true, detail: 'Le thé en vrac coûte 3-5x moins que les sachets. 100g de thé vert vrac (~3€) = 40-50 tasses. Soit 6-7 centimes par tasse. Riche en antioxydants, minéraux, L-théanine.' },
  { icon: '☕', name: 'Café filtre maison', rec: '1-2/jour', ok: null, detail: 'Café filtre moulu (100g ~1.50€) = 15-20 cafés = 8-10 centimes par tasse vs 1.50-3€ au bar. Économie de 30-60€/mois pour un consommateur régulier.' },
  { icon: '🌿', name: 'Tisanes maison', rec: 'Le soir', ok: true, detail: 'Tisanes vrac en herboristerie : camomille, menthe, verveine à 2-5€ les 100g. 3-4x moins chers que les sachets du supermarché. Infuser dans une boule à thé.' },
  { icon: '🧃', name: 'Jus citron eau chaude', rec: 'Le matin', ok: true, detail: 'Citron pressé dans eau chaude : coût ~0.15€ par verre. Vitamine C, digestion stimulée, goût agréable. Remplace les eaux aromatisées industrielles (0.60-1€/bouteille).' },
  { icon: '🧋', name: 'Sodas et boissons sucrées', rec: 'À éviter (budget + santé)', ok: false, detail: 'Un pack de sodas (6x1.5L ~6€) = calories vides, sucre, acides, additifs. Ce budget dépensé en fruits et légumes apporte une valeur nutritive 10-20x supérieure.' },
];

export const BUDGET_RECIPES = [
  { id: 'bg1', title: 'Mujaddara (riz, lentilles, oignons)', category: 'budget-serre', meal_category: 'dejeuner',
    calories: 420, proteins: 16, carbs: 68, fats: 8, prep_time: 5, cook_time: 30, servings: 4, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop',
    description: 'Plat national libanais : protéines complètes pour 0.35€/portion. 3000 ans d\'histoire culinaire.',
    ingredients: ['200g riz complet', '200g lentilles vertes sèches', '3 oignons', '4 c.à.s huile olive', '1 c.à.c cumin', '1 c.à.c cannelle', 'Sel, poivre', 'Yaourt nature pour servir'],
    steps: ['Cuire les lentilles 20 min dans l\'eau bouillante', 'Cuire le riz en parallèle', 'Émincer finement les oignons, caraméliser 20-25 min à feu doux dans l\'huile', 'Mélanger riz + lentilles + épices', 'Garnir d\'oignons caramélisés', 'Servir avec yaourt nature et salade'],
    dietitian_tips: 'Riz + lentilles = protéines complètes (tous les acides aminés essentiels). Plat végétarien aussi nutritif que de la viande.',
    allergy_alternatives: 'Sans allergènes majeurs. Naturellement sans gluten.',
    tags: ['budget', 'végétarien', 'protéines-complètes', 'anti-gaspi'] },
  { id: 'bg2', title: 'Dal de pois cassés à l\'indienne', category: 'budget-serre', meal_category: 'diner',
    calories: 380, proteins: 20, carbs: 55, fats: 10, prep_time: 5, cook_time: 25, servings: 3, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop',
    description: 'Cuisine indienne 100% végétale et économique. Riche en protéines, fibres et épices anti-inflammatoires.',
    ingredients: ['250g pois cassés', '1 boîte tomates concassées', '1 oignon', '2 gousses ail', '1 cm gingembre frais', '1 c.à.c curcuma', '1 c.à.c garam masala', '1 c.à.s huile', 'Sel, coriandre'],
    steps: ['Rincer les pois cassés', 'Faire revenir oignon + ail + gingembre', 'Ajouter les épices 30 sec', 'Ajouter tomates + pois cassés + eau (500ml)', 'Cuire 25 min jusqu\'à consistance crémeuse', 'Servir avec riz et coriandre fraîche'],
    dietitian_tips: 'Le curcuma + poivre noir = absorption de la curcumine x20. Ne jamais mettre le curcuma sans poivre.',
    allergy_alternatives: 'Sans allergènes majeurs. Naturellement sans gluten et végétalien.',
    tags: ['budget', 'végétalien', 'anti-inflammatoire', 'inde'] },
  { id: 'bg3', title: 'Soupe de légumes anti-gaspi', category: 'budget-serre', meal_category: 'diner',
    calories: 180, proteins: 8, carbs: 28, fats: 5, prep_time: 10, cook_time: 25, servings: 4, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop',
    description: 'La soupe qui utilise tous les légumes qui fléchissent dans le frigo. Zéro gaspi, maximum nutrition.',
    ingredients: ['Tous les légumes qui fléchissent (carottes, courgettes, pommes de terre, céleri...)', '1 oignon', '2 gousses ail', '1 c.à.s huile', '500ml bouillon légumes ou eau', 'Herbes, sel, poivre', 'Pain complet pour servir'],
    steps: ['Couper tous les légumes grossièrement', 'Faire revenir oignon + ail', 'Ajouter tous les légumes + bouillon', 'Cuire 20-25 min', 'Mixer finement (veloutée) ou laisser en morceaux', 'Ajuster assaisonnement'],
    dietitian_tips: 'La soupe est le plat anti-gaspi par excellence. Elle valorise n\'importe quel légume quelle que soit sa texture.',
    allergy_alternatives: 'Sans allergènes selon les légumes utilisés. Naturellement végétalien.',
    tags: ['anti-gaspi', 'budget', 'végétalien', 'toutes-saisons'] },
  { id: 'bg4', title: 'Frittata de fond de frigo', category: 'budget-serre', meal_category: 'diner',
    calories: 320, proteins: 22, carbs: 14, fats: 20, prep_time: 10, cook_time: 15, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&auto=format&fit=crop',
    description: 'La frittata italienne pour finir les restes de légumes de la semaine. Économique et délicieux.',
    ingredients: ['4-5 œufs', 'Tous les légumes restants (cuits ou crus)', 'Fromage râpé (fin de bloc)', '1 c.à.s huile', 'Herbes fraîches ou sèches', 'Sel, poivre'],
    steps: ['Préchauffer four 180°C', 'Faire sauter les légumes 5 min', 'Battre les œufs avec sel, poivre', 'Verser les œufs sur les légumes', 'Ajouter le fromage', 'Terminer au four 10 min jusqu\'à doré'],
    dietitian_tips: 'La frittata est l\'équivalent italien de l\'omelette mais plus épaisse et passée au four : moins de matière grasse, plus simple à réussir.',
    allergy_alternatives: 'Sans lactose : sans fromage ou avec levure nutritionnelle.',
    tags: ['anti-gaspi', 'budget', 'vendredi-soir', 'restes'] },
];

export const BUDGET_BLOGS = [
  { id: 'bg-b1', title: 'Manger sain à moins de 3€ par jour : le guide complet',
    excerpt: '3€ par jour pour une alimentation équilibrée. Légumineuses, œufs, légumes de saison, anti-gaspi : les stratégies des diététiciennes pour les petits budgets.',
    content: `## C'est possible : le budget et la santé ne s'opposent pas\n\nContrairement aux idées reçues, l'alimentation saine peut coûter moins cher que les aliments ultra-transformés.\n\n## Le coût comparé des protéines (pour 20g de protéines)\n| Source | Prix |\n|--------|------|\n| Lentilles sèches | 0.15€ |\n| Œufs | 0.35€ |\n| Sardines boîte | 0.60€ |\n| Poulet | 1.20€ |\n| Thon boîte | 0.80€ |\n| Steak haché | 2.50€ |\n| Saumon | 3.50€ |\n\n## Les 10 aliments les plus nutritifs et économiques\n1. **Lentilles** : 0.15€ la portion protéinée\n2. **Œufs** : 0.18€ pièce\n3. **Flocons d'avoine** : 0.09€ le petit-déjeuner\n4. **Riz complet** : 0.15€ la portion\n5. **Sardines** : 0.60€ la portion protéinée\n6. **Carottes** : 0.25€ la portion\n7. **Épinards surgelés** : 0.22€ la portion\n8. **Banane** : 0.25€ pièce\n9. **Yaourt nature** : 0.30€ le pot\n10. **Chocolat noir 70%** : 0.30€ les 2 carrés\n\n## Les stratégies anti-gaspi qui font économiser\n- **FIFO** : First In First Out dans le frigo\n- **La liste** : jamais de courses sans liste\n- **Le congélateur** : tout ce qui approche de la DLC\n- **Les portions** : cuire en grande quantité, consommer sur 4 jours`,
    category: 'budget-serre', read_time: 7 },
];