export const EMPLOI_WEEKS = [
  {
    num: 1, title: 'Semaine 1 – Organisation & meal prep', color: 'from-slate-100 to-gray-100',
    objective: 'Mettre en place le système de préparation hebdomadaire',
    habits: ['Dédicacer 1h30 le dimanche au batch cooking', 'Préparer 5 lunch boxes le dimanche soir', 'Acheter des contenants hermétiques de qualité'],
    nutrition: 'Cuisson en grande quantité, assemblage rapide',
    nutritionDetail: ['Cuire 500g de céréales pour 5 repas', 'Rôtir 1 plateau de protéines et légumes', 'Préparer 5 portions, vinaigrette maison (2 semaines)'],
    mealExample: 'Bowl : riz complet + poulet rôti + légumes rôtis + sauce soja + sésame',
    activity: 'Marche pendant la pause déjeuner (20 min)',
    activityDetail: ['La marche déjeuner décompresse et améliore la digestion', 'Coupe avec le travail = retour plus productif l\'après-midi', 'Même 10 min valent mieux que rien'],
    checklist: ['Batch cooking dimanche', '5 lunch boxes prêtes', 'Contenants hermétiques', 'Marche déjeuner'],
    tip: '1h30 le dimanche = 5 déjeuners assurés. Calcul : 18 min par repas au lieu de 45 min en semaine.',
  },
  {
    num: 2, title: 'Semaine 2 – Petit-déjeuner express mais complet', color: 'from-gray-100 to-zinc-100',
    objective: 'Gagner du temps le matin sans sacrifier la nutrition',
    habits: ['Préparer les overnight oats la veille', 'Couper les fruits le dimanche', 'Préparer des pancakes batch congelés'],
    nutrition: 'Préparation la veille pour 0 min le matin',
    nutritionDetail: ['Overnight oats : 2 min le soir, 0 min le matin', 'Smoothie bags congelés : sortir un sachet, mixer 60 sec', 'Œufs durs (5 jours frigo) : toujours prêts', 'Pain congelé tranché : décongèle en 2 min'],
    mealExample: 'Overnight oats : avoine + yaourt + fruits + chia → prêt au réveil',
    activity: '10 min de sport au réveil (yoga, gainage)',
    activityDetail: ['10 min de mouvement dès le réveil = dopamine + meilleure journée', 'Yoga au lit : accessible, aucun équipement', 'App 7-min workout : entraînement complet en 7 minutes'],
    checklist: ['Overnight oats préparés', 'Fruits coupés', 'Œufs durs frigo', '10 min sport matin'],
    tip: 'Le temps du matin est précieux. Préparez tout la veille : tenue, sac, repas. Gagnez 15-20 minutes.',
  },
  {
    num: 3, title: 'Semaine 3 – Dîners en moins de 15 minutes', color: 'from-zinc-100 to-slate-100',
    objective: 'Des recettes saines pour personne épuisée le soir',
    habits: ['Maîtriser 5 recettes en moins de 15 minutes', 'Toujours avoir les ingrédients de base en stock', 'Cuisiner en double le soir pour déjeuner le lendemain'],
    nutrition: 'Protéines rapides + légumes + glucides de qualité',
    nutritionDetail: ['Œufs brouillés : 5 min, protéines complètes', 'Pasta : 12 min, légumes + glucides + fromage', 'Soupe conserve améliorée : 8 min', 'Sardines + riz micro-ondes + légumes surgelés : 8 min'],
    mealExample: 'Omelette 3 œufs + légumes surgelés poêlés + pain complet = 10 min, équilibré',
    activity: 'Décompression active après le travail',
    activityDetail: ['15 min de marche entre bureau et maison', 'Coupe mentale travail-maison : réduit le cortisol', 'Étirements 10 min après dîner : meilleure qualité du sommeil'],
    checklist: ['5 recettes <15 min maîtrisées', 'Placard de base plein', 'Double portion soir', 'Décompression active'],
    tip: 'Les œufs sont le super-aliment de l\'emploi chargé : 5 min, protéines complètes, vitamine D, choline, B12.',
  },
  {
    num: 4, title: 'Semaine 4 – Alimentation et performance au travail', color: 'from-blue-100 to-slate-100',
    objective: 'Optimiser la concentration et l\'énergie cognitive',
    habits: ['Déjeuner loin de l\'écran', 'Éviter les repas hypercaloriques le midi', 'Hydrater abondamment au bureau'],
    nutrition: 'Repas léger le midi pour rester alerte l\'après-midi',
    nutritionDetail: ['Repas trop lourd = 70% flux sanguin vers digestion', 'Protéines + légumes + glucides modérés = énergie stable 4-5h', 'Éviter fast-food les jours chargés', 'Café après 14h = sommeil dégradé'],
    mealExample: 'Salade composée + protéine + féculents modérés + eau = bureau alerte l\'après-midi',
    activity: 'Micro-pauses actives toutes les heures',
    activityDetail: ['Debout 2 min toutes les heures, 10 squats ou marche', 'La sédentarité prolongée = 2e risque cardiovasculaire après le tabac', 'Bureau debout ou ball de yoga : réduisent la sédentarité'],
    checklist: ['Déjeuner sans écran', 'Repas léger midi', 'Hydratation bureau', 'Micro-pauses actives'],
    tip: 'Une marche de 20 min après le déjeuner améliore la concentration de l\'après-midi de 15-20%.',
  },
];

export const EMPLOI_DAY = {
  label: 'Journée type emploi chargé',
  subtitle: 'Maximum nutrition, minimum temps',
  image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&auto=format&fit=crop',
  totalKcal: '2000 kcal',
  meals: [
    { icon: '🌅', name: 'Petit-déjeuner (5 min)', time: '7h00', kcal: 420,
      items: ['Overnight oats préparés la veille', '1 fruit (banane, pomme, kiwi)', 'Café ou thé noir'],
      alt: '2 tranches pain complet + beurre de cacahuète + fruit' },
    { icon: '🍱', name: 'Lunch box (batch dimanche)', time: '12h30', kcal: 600,
      items: ['Bowl riz complet 150g', 'Protéine rôtie (poulet, saumon, tofu) 130g', 'Légumes rôtis variés', 'Sauce vinaigrette maison', '1 fruit'],
      alt: 'Salade composée + thon + pois chiches + légumes' },
    { icon: '🍎', name: 'Collation bureau', time: '16h00', kcal: 180,
      items: ['Poignée d\'amandes (20g)', '1 fruit ou fromage blanc'],
      alt: '2 carrés chocolat noir 85% + noix' },
    { icon: '🌙', name: 'Dîner express (15 min)', time: '20h00', kcal: 560,
      items: ['Omelette 3 œufs + légumes surgelés', 'ou Pâtes complètes + sauce tomate + fromage', 'Pain au levain', '1 carré chocolat noir'],
      alt: 'Soupe légumes + pain + fromage + yaourt' },
  ],
};

export const EMPLOI_SHOPPING = [
  { cat: '🥩 Protéines rapides', items: ['Blancs de poulet x4', 'Filets de saumon x2', 'Œufs (12)', 'Thon conserve x4 boîtes', 'Sardines x3 boîtes', 'Fromage blanc (1kg)'] },
  { cat: '🌾 Féculents batch', items: ['Riz complet (500g)', 'Pâtes complètes (1kg)', 'Quinoa (300g)', 'Pain au levain (2 miches)', 'Flocons avoine (500g)'] },
  { cat: '🥦 Légumes batch', items: ['Patates douces (1kg)', 'Poivrons (4)', 'Courgettes (1kg)', 'Brocoli (2)', 'Épinards surgelés (1kg)', 'Légumes surgelés mélange (1kg)'] },
  { cat: '🍌 Fruits', items: ['Bananes (1 régime)', 'Pommes (6)', 'Kiwis (6)', 'Myrtilles (200g)'] },
  { cat: '🛢️ Placard rapide', items: ['Huile olive', 'Sauce soja', 'Conserves tomates x4', 'Chocolat noir 85%', 'Amandes (200g)', 'Noix (150g)', 'Beurre de cacahuète'] },
];

export const EMPLOI_SPORT = [
  { icon: '🧘', title: 'Yoga du matin (10 min)',
    desc: '10 min de yoga dès le réveil active le cortisol positif et améliore la productivité de la matinée.',
    detail: { intro: 'Des études de Stanford montrent que les personnes qui commencent par 10 min d\'activité physique le matin prennent de meilleures décisions et sont plus productives dans les 3 premières heures.',
      points: ['Yoga with Adriene : séries "morning yoga" 10 min YouTube', 'Gainage plancher 3x1 min = core, posture, sans équipement', 'Étirements cervicaux et épaules : essentiels pour travailleurs sur écran', 'Cohérence cardiaque 5 min juste après : potentialise les effets'],
      example: 'Réveil → verre d\'eau → 10 min yoga YouTube → douche → petit-déjeuner. 35 min qui changent la qualité de la journée.',
      tip: 'Tapis déroulé la veille au soir : lever la barrière d\'entrée réduit l\'inertie matinale.' } },
  { icon: '🚶', title: 'Marche déjeuner active',
    desc: '20 min après le repas de midi : améliore la concentration, réduit le coup de barre de 14h.',
    detail: { intro: 'La marche post-déjeuner réduit la glycémie post-prandiale de 25-30% et améliore les performances cognitives dans les 2 heures suivantes.',
      points: ['Même 10 min suffisent si pas plus de temps', 'Laisser le téléphone au bureau = décompression mentale', 'Avec un collègue : networking + bien-être', 'Sans casque : attention à l\'environnement'],
      example: 'Tour du pâté de maisons, parc proche, ou 10 min d\'escaliers du bâtiment.',
      tip: 'Si impossible de sortir : 5 min couloirs + 5 min escaliers = bénéfice réduit mais réel.' } },
  { icon: '🏋️', title: 'Sport express weekend',
    desc: '2 séances de 45 min le week-end = "warrior workout". L\'accumulation suffit selon l\'OMS.',
    detail: { intro: 'L\'OMS reconnaît que l\'activité physique peut être accumulée en moins de séances mais plus intenses. Deux séances de 45-75 min week-end = recommandations hebdomadaires.',
      points: ['Samedi : 45 min course ou HIIT', 'Dimanche : 45 min vélo ou natation', 'Ou une session 1h30 le dimanche matin', 'Intensité modérée à élevée pour compenser la fréquence réduite'],
      example: 'Samedi : parkrun 5km (gratuit, 30 min) + retour à pied (30 min). Total : 1h, aucun frais.',
      tip: 'Réservez le sport week-end comme un rendez-vous professionnel : dans l\'agenda, inamovible.' } },
  { icon: '🖥️', title: 'Micro-pauses actives bureau',
    desc: 'Debout 2 min toutes les heures : réduisent les risques cardiovasculaires de 40%.',
    detail: { intro: 'La sédentarité prolongée est un facteur de risque cardiovasculaire indépendant, même chez les sportifs. Se lever toutes les heures réduit drastiquement ces risques.',
      points: ['Alarme toutes les 50 min = signal pour se lever', '10 squats, 20 mollets, 2 min de marche = suffisant', 'Réunions debout ou en marchant', 'Printer à l\'étage : obligation de bouger'],
      example: 'Méthode Pomodoro + sport : 25 min focus → 5 min debout + étirements. Productivité + santé.',
      tip: 'Bureau assis-debout : investissement rentabilisé en quelques mois de santé améliorée.' } },
];

export const EMPLOI_DRINKS = [
  { icon: '💧', name: 'Eau bureau (1.5-2L)', rec: 'Gourde visible sur le bureau', ok: true, detail: 'Gourde de 500ml sur le bureau. Objectif : la remplir 3-4 fois. La déshydratation légère réduit la productivité et la concentration.' },
  { icon: '☕', name: 'Café (max 2 avant 14h)', rec: '1 matin, 1 avant 14h', ok: null, detail: 'La caféine a une demi-vie de 5-7h. Un café à 15h est encore à moitié actif à 22h, dégradant le sommeil.' },
  { icon: '🍵', name: 'Thé vert l\'après-midi', rec: '1-2 tasses après 14h', ok: true, detail: 'Après 14h, thé vert à la place du café. Caféine légère + L-théanine = concentration calme sans crash de 17h.' },
  { icon: '🍋', name: 'Eau citronnée', rec: 'Matin à jeun', ok: true, detail: 'Grand verre d\'eau + jus d\'un demi-citron le matin : active la digestion, vitamine C, encourage la bonne hydratation.' },
  { icon: '🥤', name: 'Smoothie bag congelé', rec: 'Petit-déjeuner ou collation', ok: true, detail: 'Préparer des smoothie bags le dimanche (ingrédients congelés). Matin : sortir un bag, mixer avec yaourt. 2 min, nutritif.' },
  { icon: '🍺', name: 'Apéro after-work', rec: 'Max 1-2/semaine', ok: false, detail: 'L\'alcool régulier dégrade le sommeil, augmente le cortisol et réduit la récupération. Non-négociable pour les actifs.' },
];

export const EMPLOI_RECIPES = [
  { id: 'em1', title: 'Overnight oats préparés la veille', category: 'emploi-charge', meal_category: 'petitdej',
    calories: 380, proteins: 14, carbs: 55, fats: 10, prep_time: 5, cook_time: 0, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?w=600&auto=format&fit=crop',
    description: '5 minutes le soir, 0 minute le matin. La recette parfaite pour l\'emploi chargé.',
    ingredients: ['40g flocons d\'avoine', '150ml yaourt grec ou lait végétal', '1 c.à.s graines chia', '1 c.à.c miel', '1/2 banane ou fruits rouges', 'Noix selon goût'],
    steps: ['La veille : mélanger avoine + yaourt + chia + miel dans un bocal', 'Fermer et mettre au frigo', 'Le matin : sortir du frigo, garnir de fruits et noix frais', 'Manger directement dans le bocal'],
    dietitian_tips: 'Les graines de chia absorbent 10x leur volume en eau : avoine crémeuse et rassasiante.',
    allergy_alternatives: 'Sans lactose : lait végétal. Sans gluten : avoine certifiée GF.',
    tags: ['batch', 'rapide', 'emploi-chargé', 'zéro-vaisselle'] },
  { id: 'em2', title: 'Bowl batch hebdomadaire', category: 'emploi-charge', meal_category: 'dejeuner',
    calories: 550, proteins: 38, carbs: 52, fats: 18, prep_time: 10, cook_time: 30, servings: 5, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop',
    description: '30 min le dimanche = 5 déjeuners équilibrés en semaine.',
    ingredients: ['500g riz complet ou quinoa', '600g poulet ou saumon', '1kg légumes variés', '4 c.à.s huile olive', 'Épices (paprika, cumin, curcuma)', 'Sauce citron + huile + ail'],
    steps: ['Four 200°C', 'Cuire les céréales (20-25 min)', 'Légumes + protéine + huile + épices sur plaque', 'Rôtir 25-30 min', 'Diviser en 5 contenants hermétiques', 'Sauce dans pot séparé', 'Conservation : 4 jours au frigo'],
    dietitian_tips: 'La sauce à part conserve la fraîcheur et évite que le repas détrempe.',
    allergy_alternatives: 'Végétarien : tofu ferme + pois chiches.',
    tags: ['batch-hebdo', 'lunch-box', '5-repas'] },
  { id: 'em3', title: 'Omelette express légumes surgelés', category: 'emploi-charge', meal_category: 'diner',
    calories: 360, proteins: 26, carbs: 12, fats: 24, prep_time: 2, cook_time: 8, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&auto=format&fit=crop',
    description: 'La recette d\'urgence : frigo vide, fatigué, 10 minutes.',
    ingredients: ['3 œufs', '100g légumes surgelés', '30g fromage râpé', '1 c.à.c huile olive', 'Sel, herbes de Provence'],
    steps: ['Chauffer l\'huile, jeter les légumes surgelés', 'Cuire 3-4 min', 'Battre les œufs, verser', 'Cuire à feu doux, fromage au milieu', 'Plier et servir avec pain'],
    dietitian_tips: 'Les légumes surgelés sont aussi nutritifs que les frais.',
    allergy_alternatives: 'Sans lactose : avocat à la place du fromage.',
    tags: ['10-min', 'urgence', 'nutritif'] },
  { id: 'em4', title: 'Pâtes express sauce tomate thon', category: 'emploi-charge', meal_category: 'diner',
    calories: 480, proteins: 25, carbs: 62, fats: 14, prep_time: 3, cook_time: 12, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&auto=format&fit=crop',
    description: '15 min, équilibré, satisfaisant. La sauce tomate améliorée.',
    ingredients: ['100g pâtes complètes', '1 boîte tomates concassées', '1 boîte thon', '1 gousse ail', '1 c.à.s huile olive', 'Basilic', 'Parmesan'],
    steps: ['Cuire les pâtes al dente', 'Faire revenir ail dans l\'huile', 'Ajouter tomates + thon', 'Cuire 5 min', 'Mélanger avec pâtes égouttées', 'Parmesan et basilic'],
    dietitian_tips: 'Le thon en conserve est riche en B12 et sélénium.',
    allergy_alternatives: 'Sans gluten : pâtes de riz. Végétarien : lentilles.',
    tags: ['15-min', 'conserves', 'budget'] },
];

export const EMPLOI_BLOGS = [
  { id: 'em-b1', title: 'Le batch cooking de dimanche : la méthode complète',
    excerpt: '1h30 le dimanche pour 5 déjeuners et 3 dîners préparés. La méthode pas à pas.',
    content: `## Pourquoi le batch cooking change tout\n\nSans organisation, les actifs mangent mal ou sautent des repas. Le batch cooking résout ce problème.\n\n## Le système en 5 étapes\n\n### 1. La liste (15 min vendredi)\nChoisir 3-4 recettes, faire la liste de courses.\n\n### 2. Les courses (samedi)\nMarché ou drive pour économiser du temps.\n\n### 3. Le batch (1h-1h30 dimanche)\n**En parallèle :**\n- Four : légumes + protéines (30 min)\n- Casserole 1 : céréales\n- Casserole 2 : légumineuses\n- Pendant la cuisson : sauces, légumes crus\n\n### 4. Le conditionnement (15 min)\nPortions individuelles, étiquetées avec la date.\n\n### 5. L'assemblage en semaine (3 min)\nSortir un contenant, ajouter une sauce, réchauffer.\n\n## La règle des 3 composantes\n1. **Protéines** : poulet, saumon, thon, tofu, lentilles\n2. **Glucides** : riz complet, quinoa, patate douce\n3. **Légumes** : rôtis, crus, en salade\n\n## Conservation\n- Riz et légumineuses : 4-5 jours\n- Légumes rôtis : 4 jours\n- Protéines cuites : 3-4 jours`,
    category: 'emploi-charge', read_time: 8 },
];