export const PRISE_MASSE_WEEKS = [
  {
    num: 1,
    title: "Semaine 1 - Relancer l'appetit",
    color: 'from-emerald-100 to-lime-100',
    objective: 'Ajouter 250 a 300 kcal par jour sans lourdeur digestive',
    habits: ['Ajouter une collation simple chaque jour', 'Boire hors des repas pour garder de l appetit', 'Garder 3 repas complets et reguliers'],
    nutrition: 'Surplus progressif, portions digestes',
    nutritionDetail: ['Ajouter huile olive, avocat, fromage blanc ou oleagineux', 'Prioriser les aliments faciles a digerer', 'Ne pas forcer avec des assiettes trop volumineuses des le depart'],
    mealExample: 'Skyr + banane + flocons avoine + beurre de cacahuete',
    activity: 'Reprise technique, 3 seances courtes',
    activityDetail: ['Travailler les mouvements de base', 'Garder 2 repetitions en reserve', 'Marcher 20 minutes les jours sans entrainement'],
    checklist: ['Collation quotidienne', '3 repas complets', 'Hydratation', 'Sommeil suivi'],
    tip: 'Une prise de masse propre se gagne surtout avec la regularite. Le surplus doit monter doucement.',
  },
  {
    num: 2,
    title: 'Semaine 2 - Proteines a chaque repas',
    color: 'from-lime-100 to-yellow-100',
    objective: 'Atteindre un apport proteique stable sur la journee',
    habits: ['Inclure une source de proteines au petit-dejeuner', 'Preparer deux bases proteinees a l avance', 'Ajouter une collation post-entrainement'],
    nutrition: 'Proteines reparties sur 4 a 5 prises',
    nutritionDetail: ['Oeufs, poulet, tofu, poisson, skyr, legumes secs', 'Viser une portion proteinee a chaque repas', 'Associer glucides et proteines apres le sport'],
    mealExample: 'Riz complet + poulet + legumes + huile olive + yaourt grec',
    activity: 'Progression douce en renforcement',
    activityDetail: ['Noter les charges ou repetitions', 'Augmenter un seul parametre a la fois', 'Conserver une technique propre'],
    checklist: ['Proteines matin', 'Batch proteines', 'Post-training', 'Journal sport'],
    tip: 'Mieux vaut 25 a 35 g de proteines plusieurs fois dans la journee qu une seule grosse prise le soir.',
  },
  {
    num: 3,
    title: 'Semaine 3 - Glucides utiles',
    color: 'from-yellow-100 to-amber-100',
    objective: 'Soutenir les entrainements avec des glucides de qualite',
    habits: ['Ajouter une portion de feculents autour du sport', 'Garder des legumes a chaque repas', 'Prevoir une option rapide les jours charges'],
    nutrition: 'Energie stable pour performer',
    nutritionDetail: ['Riz, pates completes, pommes de terre, flocons avoine', 'Fruit + yaourt ou tartine avant seance si besoin', 'Eviter de tout miser sur sucre et snacks'],
    mealExample: 'Pates completes + saumon + courgettes + parmesan',
    activity: 'Seances plus structurees',
    activityDetail: ['3 a 4 seances par semaine selon recuperation', 'Mettre les exercices polyarticulaires en debut', 'Finir par 5 a 10 minutes de mobilite'],
    checklist: ['Feculents sport', 'Legumes', 'Option rapide', 'Mobilite'],
    tip: 'Les glucides ne sont pas l ennemi en prise de masse : ils aident a mieux s entrainer et a mieux recuperer.',
  },
  {
    num: 4,
    title: 'Semaine 4 - Stabiliser le rythme',
    color: 'from-amber-100 to-orange-100',
    objective: 'Ancrer les habitudes et ajuster selon l evolution du poids',
    habits: ['Se peser 2 a 3 fois par semaine au reveil', 'Ajuster les portions selon la tendance', 'Planifier les courses avant la semaine'],
    nutrition: 'Ajustement fin du surplus',
    nutritionDetail: ['Si le poids ne bouge pas, ajouter 150 a 200 kcal', 'Si la digestion est lourde, fractionner davantage', 'Garder une qualite alimentaire elevee'],
    mealExample: 'Bowl quinoa + steak hache 5% + avocat + legumes rotis',
    activity: 'Recuperation et surcharge progressive',
    activityDetail: ['Dormir 7 a 9 heures autant que possible', 'Garder au moins un jour plus leger', 'Augmenter les charges seulement si la forme suit'],
    checklist: ['Poids suivi', 'Courses planifiees', 'Surplus ajuste', 'Repos'],
    tip: 'Une evolution de 0,25 a 0,5 kg par semaine est souvent plus propre et plus durable.',
  },
];

export const PRISE_MASSE_DAY = {
  label: 'Journée type prise de masse',
  subtitle: 'Un rythme dense, digeste et facile a tenir',
  image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=900&auto=format&fit=crop',
  totalKcal: '2800',
  meals: [
    {
      icon: '🌅',
      name: 'Petit-déjeuner',
      time: '7h30',
      kcal: 620,
      items: ['Flocons d avoine', 'Lait ou boisson soja', 'Banane', 'Beurre de cacahuete', 'Skyr ou fromage blanc'],
      alt: 'Pain complet + oeufs + avocat + fruit',
    },
    {
      icon: '🥤',
      name: 'Collation',
      time: '10h30',
      kcal: 350,
      items: ['Smoothie lait', 'Fruits rouges', 'Yaourt grec', 'Miel', 'Amandes'],
      alt: 'Skyr + granola + compote',
    },
    {
      icon: '🍽️',
      name: 'Déjeuner',
      time: '12h45',
      kcal: 760,
      items: ['Riz complet', 'Poulet ou tofu', 'Legumes rotis', 'Huile olive', 'Fruit'],
      alt: 'Lentilles + quinoa + feta + huile olive',
    },
    {
      icon: '💪',
      name: 'Avant ou après sport',
      time: '16h30',
      kcal: 360,
      items: ['Pain complet', 'Beurre de cacahuete', 'Banane', 'Eau'],
      alt: 'Yaourt grec + flocons avoine + chocolat noir',
    },
    {
      icon: '🌙',
      name: 'Dîner',
      time: '20h00',
      kcal: 710,
      items: ['Pates completes', 'Saumon ou oeufs', 'Courgettes', 'Parmesan', 'Huile olive'],
      alt: 'Patate douce + haricots rouges + avocat',
    },
  ],
};

export const PRISE_MASSE_SHOPPING = [
  { cat: 'Proteines', items: ['Oeufs', 'Poulet', 'Saumon', 'Tofu', 'Skyr', 'Fromage blanc'] },
  { cat: 'Feculents', items: ['Riz complet', 'Pates completes', 'Quinoa', 'Flocons avoine', 'Patates douces', 'Pain complet'] },
  { cat: 'Energie dense', items: ['Huile olive', 'Avocats', 'Amandes', 'Beurre de cacahuete', 'Noix', 'Chocolat noir'] },
  { cat: 'Fruits et legumes', items: ['Bananes', 'Fruits rouges', 'Courgettes', 'Brocoli', 'Legumes a rotir', 'Citrons'] },
];

export const PRISE_MASSE_SPORT = [
  {
    icon: '🏋️',
    title: 'Surcharge progressive',
    desc: 'Augmenter petit a petit les repetitions, les charges ou les series.',
    detail: {
      intro: 'Le muscle progresse lorsqu il reçoit un signal un peu plus exigeant, puis assez de repos pour reconstruire.',
      points: ['Noter les performances', 'Augmenter un parametre a la fois', 'Garder une execution propre', 'Eviter l echec sur toutes les series'],
      example: 'Si vous faites 3 x 10 repetitions propres, passer a 3 x 11 ou ajouter une petite charge la seance suivante.',
      tip: 'La progression lente bat largement les grosses seances irregulieres.',
    },
  },
  {
    icon: '🛌',
    title: 'Sommeil prioritaire',
    desc: 'Le surplus alimentaire fonctionne mieux avec une vraie recuperation.',
    detail: {
      intro: 'Le sommeil soutient la synthese proteique, les hormones de recuperation et la motivation.',
      points: ['Viser 7 a 9 heures', 'Garder une heure de coucher stable', 'Limiter les ecrans tardifs', 'Eviter les repas trop lourds juste avant de dormir'],
      example: 'Diner 2 heures avant le coucher, puis collation legere si besoin.',
      tip: 'Sans sommeil, la prise de masse devient plus lente et plus fatigante.',
    },
  },
  {
    icon: '🚶',
    title: 'Activite douce',
    desc: 'Bouger un peu aide l appetit et la digestion sans nuire au surplus.',
    detail: {
      intro: 'La marche maintient la digestion, le cardio de base et la recuperation active.',
      points: ['15 a 30 minutes par jour', 'Rester en intensite facile', 'Marcher apres un gros repas si digestion lente', 'Ne pas compenser avec trop de cardio intense'],
      example: 'Une marche de 20 minutes apres le dejeuner les jours sans entrainement.',
      tip: 'Le but est de mieux assimiler, pas de bruler tout le surplus.',
    },
  },
];

export const PRISE_MASSE_DRINKS = [
  { icon: '💧', name: 'Eau', rec: '1,5 a 2 L par jour', ok: true, detail: 'Une bonne hydratation aide les performances, la digestion et la recuperation.' },
  { icon: '🥛', name: 'Lait ou boisson soja', rec: 'Selon tolerance', ok: true, detail: 'Pratique pour ajouter des calories et des proteines sans gros volume alimentaire.' },
  { icon: '🍌', name: 'Smoothie maison', rec: '1 collation si besoin', ok: true, detail: 'Banane, lait, yaourt grec et flocons avoine donnent une collation dense et facile a boire.' },
  { icon: '☕', name: 'Cafe', rec: 'Avant 15h', ok: null, detail: 'Utile avant une seance, mais a limiter si le sommeil baisse.' },
  { icon: '🧃', name: 'Sodas', rec: 'Occasionnel', ok: false, detail: 'Ils ajoutent des calories mais peu de nutriments. Mieux vaut garder la place pour des aliments utiles.' },
];

export const PRISE_MASSE_RECIPES = [
  {
    id: 'pm1',
    title: 'Porridge banane cacahuete',
    category: 'prise-masse',
    meal_category: 'petitdej',
    calories: 620,
    proteins: 28,
    carbs: 78,
    fats: 22,
    prep_time: 5,
    cook_time: 5,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=700&auto=format&fit=crop',
    description: 'Un petit-dejeuner dense, rapide et facile a ajuster.',
    ingredients: ['70g flocons avoine', '250ml lait', '1 banane', '1 c. a s. beurre de cacahuete', '150g skyr'],
    steps: ['Chauffer avoine et lait 5 min', 'Ajouter la banane en rondelles', 'Finir avec skyr et beurre de cacahuete'],
    dietitian_tips: 'Ajoutez 10g de noix si le poids ne monte pas apres deux semaines.',
    allergy_alternatives: 'Remplacer le lait par une boisson soja et la cacahuete par puree amande.',
    tags: ['dense', 'rapide', 'petit-dejeuner'],
  },
  {
    id: 'pm2',
    title: 'Bowl poulet riz avocat',
    category: 'prise-masse',
    meal_category: 'dejeuner',
    calories: 760,
    proteins: 45,
    carbs: 82,
    fats: 28,
    prep_time: 10,
    cook_time: 18,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=700&auto=format&fit=crop',
    description: 'Un dejeuner complet pour soutenir les entrainements.',
    ingredients: ['180g riz cuit', '150g poulet', '1/2 avocat', 'Legumes rotis', '1 c. a s. huile olive'],
    steps: ['Cuire le riz', 'Griller le poulet', 'Assembler avec legumes et avocat', 'Ajouter huile olive et citron'],
    dietitian_tips: 'L avocat et l huile olive montent les calories sans trop augmenter le volume.',
    allergy_alternatives: 'Remplacer le poulet par tofu grille ou pois chiches.',
    tags: ['dejeuner', 'proteines', 'batch-cooking'],
  },
  {
    id: 'pm3',
    title: 'Pates saumon courgettes',
    category: 'prise-masse',
    meal_category: 'diner',
    calories: 710,
    proteins: 42,
    carbs: 76,
    fats: 26,
    prep_time: 10,
    cook_time: 15,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=700&auto=format&fit=crop',
    description: 'Diner riche en omega-3, glucides utiles et proteines.',
    ingredients: ['90g pates completes crues', '130g saumon', '1 courgette', 'Parmesan', 'Huile olive'],
    steps: ['Cuire les pates', 'Poeler courgette et saumon', 'Assembler avec parmesan et huile olive'],
    dietitian_tips: 'Tres bon repas apres entrainement si vous avez besoin de refaire les reserves.',
    allergy_alternatives: 'Remplacer saumon par oeufs ou tofu fume.',
    tags: ['diner', 'omega-3', 'recuperation'],
  },
  {
    id: 'pm4',
    title: 'Smoothie prise de masse',
    category: 'prise-masse',
    meal_category: 'collation',
    calories: 480,
    proteins: 24,
    carbs: 62,
    fats: 16,
    prep_time: 5,
    cook_time: 0,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=700&auto=format&fit=crop',
    description: 'La collation facile quand manger plus devient difficile.',
    ingredients: ['250ml lait', '1 banane', '150g yaourt grec', '30g flocons avoine', '1 c. a s. miel'],
    steps: ['Mixer tous les ingredients', 'Boire frais', 'Ajouter de l eau si texture trop epaisse'],
    dietitian_tips: 'Les calories liquides sont utiles quand l appetit bloque.',
    allergy_alternatives: 'Utiliser boisson soja et yaourt vegetal enrichi.',
    tags: ['collation', 'smoothie', 'rapide'],
  },
];
