// ─── DONNÉES PROGRAMME RÉÉQUILIBRAGE ALIMENTAIRE ─────────────────────────────

export const REEQUILIBRAGE_WEEKS = [
  {
    num: 1, title: "Observer ses habitudes",
    objective: "Prendre conscience de ses habitudes actuelles sans jugement",
    color: 'from-green-50 to-primary/5',
    habits: ["Tenir un journal alimentaire 7 jours", "Noter l'heure des repas", "Repérer les grignotages", "Observer sa faim avant et après chaque repas"],
    nutrition: "Cette semaine, ne changez rien. Observez seulement. Notez ce que vous mangez, quand, et dans quel contexte (stress, ennui, faim réelle).",
    nutritionDetail: [
      "Utilisez votre téléphone ou un carnet pour noter chaque repas et collation.",
      "Notez aussi votre faim (de 1 à 5) avant de manger et votre satiété après.",
      "Repérez les moments de grignotage automatique (devant la télé, au travail...).",
      "Observez les émotions liées à la nourriture sans vous juger.",
    ],
    activity: "Aucune contrainte sportive cette semaine. Si vous marchez déjà, continuez. Observez aussi votre niveau d'activité habituel.",
    activityDetail: [
      "L'objectif cette semaine est uniquement l'observation, pas le changement.",
      "Notez combien de pas vous faites en moyenne par jour.",
      "Repérez les moments de sédentarité prolongée.",
      "Pas de pression : cette semaine sert de point de départ.",
    ],
    checklist: ["Journal alimentaire commencé", "Repas notés avec heures", "Grignotages identifiés", "Niveau de faim observé", "Aucun changement imposé"],
    tip: "Observer sans juger est la première étape. Vous ne pouvez pas changer ce que vous ne connaissez pas encore.",
  },
  {
    num: 2, title: "Structurer les repas",
    objective: "Installer 3 repas fixes par jour",
    color: 'from-blue-50 to-primary/5',
    habits: ["3 repas à heures fixes", "Pas de saut de repas", "S'asseoir pour manger", "Manger sans écran au moins une fois par jour"],
    nutrition: "Commencez par poser 3 repas par jour à des heures régulières. Le corps adore les rituels : quand il sait quand le prochain repas arrive, il gère mieux la faim.",
    nutritionDetail: [
      "Fixez des horaires approximatifs : petit-déj 7h-8h, déjeuner 12h-13h, dîner 19h-20h.",
      "Évitez de sauter le déjeuner même si vous n'avez pas faim : mangez moins, mais mangez.",
      "S'asseoir pour manger (même 10 min) change la relation à la nourriture.",
      "Ne mangez pas en marchant, en voiture ou devant un écran. Au moins un repas sans distraction.",
    ],
    activity: "Ajoutez 15 min de marche quotidienne si ce n'est pas déjà le cas. Pas plus.",
    activityDetail: [
      "15 minutes de marche après le dîner aide à réguler la glycémie.",
      "Pas besoin d'un sport organisé cette semaine : la régularité des repas est la priorité.",
      "Si vous ressentez plus d'énergie grâce aux repas structurés, c'est bon signe.",
    ],
    checklist: ["3 repas par jour respectés", "Aucun repas sauté", "1 repas sans écran", "Horaires approximatifs fixés", "Marche quotidienne"],
    tip: "La structure des repas réduit le grignotage de 40% en moyenne. C'est l'outil le plus simple et le plus puissant.",
  },
  {
    num: 3, title: "Ajouter des légumes sans frustration",
    objective: "Doubler la quantité de légumes au quotidien",
    color: 'from-emerald-50 to-primary/5',
    habits: ["Légumes à chaque repas principal", "Commencer le repas par les légumes", "Essayer un légume nouveau cette semaine", "Varier les cuissons (cru, vapeur, rôti)"],
    nutrition: "Pas question de supprimer quoi que ce soit. On ajoute simplement des légumes. Ils apportent fibres, vitamines, volume dans l'assiette et satiété.",
    nutritionDetail: [
      "L'objectif : au moins une portion de légumes à chaque repas principal.",
      "Commencez votre repas par une salade ou des crudités : vous mangerez moins de féculents naturellement.",
      "Les légumes rôtis au four sont très appréciés même des personnes qui 'n'aiment pas les légumes'.",
      "Conserves et surgelés comptent aussi : pois chiches, tomates, épinards surgelés = légumes valides.",
    ],
    activity: "Continuez la marche. Ajoutez 5 min d'étirements le matin si vous voulez.",
    activityDetail: [
      "Pas de changement majeur côté sport cette semaine.",
      "Les légumes améliorent l'énergie et la digestion, ce qui peut vous donner envie de bouger plus.",
    ],
    checklist: ["Légumes à chaque repas", "Repas commencé par les légumes", "1 nouveau légume testé", "Cuissons variées", "Moins de place pour les féculents"],
    tip: "Ajouter avant de supprimer. C'est le principe anti-frustration du rééquilibrage.",
  },
  {
    num: 4, title: "Rééquilibrer les petits-déjeuners",
    objective: "Commencer la journée avec un petit-déjeuner rassasiant et protéiné",
    color: 'from-orange-50 to-secondary/5',
    habits: ["Petit-déjeuner dans la première heure", "Inclure une source de protéines", "Réduire le sucre du matin", "Éviter les céréales industrielles sucrées"],
    nutrition: "Un petit-déjeuner trop sucré entraîne un coup de barre à 10h et des envies de grignoter. Un petit-déjeuner équilibré tient jusqu'au déjeuner.",
    nutritionDetail: [
      "Idéal : protéines (œufs, yaourt grec, fromage blanc) + fibres (avoine, pain complet) + 1 fruit.",
      "Exemples : toast complet + œuf poché + kiwi. Ou : porridge avoine + yaourt + fruits.",
      "Réduisez progressivement le sucre dans le café ou le thé (une cuillère de moins par semaine).",
      "Les céréales 'fitness' contiennent souvent plus de sucre qu'un biscuit. Lisez les étiquettes.",
    ],
    activity: "Optionnel : 10 min de yoga ou d'étirements le matin pour activer le corps.",
    activityDetail: [
      "Un matin actif commence par un bon petit-déjeuner.",
      "Le mouvement le matin améliore la sensibilité à l'insuline : idéal pour mieux utiliser les glucides.",
    ],
    checklist: ["Petit-déj dans la 1ère heure", "Source de protéines incluse", "Moins de sucre ajouté", "Céréales industrielles évitées", "Énergie stable jusqu'à 12h"],
    tip: "Un bon petit-déjeuner ne vous fera pas grossir. Il vous fera grignoter moins.",
  },
  {
    num: 5, title: "Choisir de meilleurs féculents",
    objective: "Remplacer les féculents raffinés par des versions complètes",
    color: 'from-yellow-50 to-primary/5',
    habits: ["Pain complet plutôt que blanc", "Riz complet ou basmati", "Pâtes complètes ou semi-complètes", "Légumineuses 3x dans la semaine"],
    nutrition: "Les féculents complets ont un index glycémique plus bas : énergie plus stable, satiété plus longue, moins d'envies sucrées l'après-midi.",
    nutritionDetail: [
      "Riz complet (IG 50) vs riz blanc (IG 72) : même plaisir, meilleure énergie.",
      "Patate douce (IG 44) : excellente alternative à la pomme de terre.",
      "Légumineuses : lentilles, pois chiches, haricots = protéines + fibres + glucides complexes.",
      "Commencez par un seul changement : remplacez le pain blanc du déjeuner par du pain complet.",
    ],
    activity: "Maintenez votre routine. Si vous le sentez, ajoutez une séance de 20 min de marche rapide.",
    activityDetail: [
      "Les féculents complexes améliorent l'endurance lors de l'effort.",
      "Pas de changement drastique côté sport cette semaine.",
    ],
    checklist: ["Pain blanc remplacé", "Riz/pâtes complets testés", "Légumineuses 3x cette semaine", "Patate douce essayée", "Énergie plus stable observée"],
    tip: "On ne supprime pas les féculents, on les choisit mieux. La satisfaction reste la même.",
  },
  {
    num: 6, title: "Gérer les envies sucrées",
    objective: "Comprendre et réduire les envies de sucre sans privation",
    color: 'from-pink-50 to-secondary/5',
    habits: ["Fruit entier si envie sucrée", "Chocolat noir 70%+ après repas", "Identifier le déclencheur de l'envie", "Boire un verre d'eau avant de craquer"],
    nutrition: "Une envie de sucre n'est pas un manque de volonté. C'est souvent le signe d'un repas insuffisant, de stress ou d'ennui. Comprendre la cause change tout.",
    nutritionDetail: [
      "Envie sucrée après le repas : signe que le repas manquait de fibres ou de protéines.",
      "Envie sucrée en milieu d'après-midi : signe d'un déjeuner insuffisant ou d'hypoglycémie.",
      "Fruit entier plutôt que jus : les fibres ralentissent l'absorption du sucre.",
      "2 carreaux de chocolat noir (70%+) = satisfait l'envie avec des polyphénols bénéfiques.",
    ],
    activity: "La marche post-repas réduit les envies sucrées de l'après-midi. Testez 15 min après le déjeuner.",
    activityDetail: [
      "La marche post-déjeuner abaisse le pic glycémique et réduit les envies de l'après-midi.",
      "Le sport en général réduit la dépendance au sucre : l'exercice libère de la dopamine.",
    ],
    checklist: ["Fruit si envie sucrée", "Chocolat noir testé", "Déclencheur identifié", "Verre d'eau avant de craquer", "Repas plus rassasiants"],
    tip: "Ne pas se priver totalement du sucre : l'interdit rend l'envie plus forte. Mieux vaut choisir consciemment.",
  },
  {
    num: 7, title: "Organiser les courses",
    objective: "Avoir toujours de bons aliments disponibles à la maison",
    color: 'from-teal-50 to-primary/5',
    habits: ["Liste de courses établie avant d'aller au supermarché", "Faire les courses le ventre plein", "Éviter les rayons ultra-transformés", "Avoir des légumes et protéines en stock"],
    nutrition: "Ce qu'on achète = ce qu'on mange. Une bonne organisation des courses est plus efficace que toute la motivation du monde.",
    nutritionDetail: [
      "Préparez votre liste à l'avance, idéalement le samedi ou dimanche matin.",
      "Faites les courses après avoir mangé : l'appétit rend les choix alimentaires moins raisonnables.",
      "Structurez vos achats : légumes, protéines, féculents complets, snacks sains.",
      "Gardez toujours en stock : oeufs, légumineuses en conserve, légumes surgelés, yaourts.",
    ],
    activity: "3 séances de marche de 20-30 min dans la semaine.",
    activityDetail: [
      "L'activité physique régulière réduit naturellement les envies d'aliments ultra-transformés.",
      "Même 3 marches de 20 min par semaine font une différence mesurable sur la santé.",
    ],
    checklist: ["Liste de courses faite avant", "Courses ventre plein", "Légumes et protéines en stock", "Snacks sains disponibles", "Rayons transformés évités"],
    tip: "Si ce n'est pas dans votre cuisine, vous ne pouvez pas le manger. Achetez ce qui vous fait du bien.",
  },
  {
    num: 8, title: "Préparer 2 repas d'avance",
    objective: "Introduire le batch cooking minimal sans que ça soit une contrainte",
    color: 'from-indigo-50 to-primary/5',
    habits: ["Préparer 2 repas supplémentaires le dimanche", "Cuire plus de céréales (riz, quinoa) pour 2-3 jours", "Préparer une soupe ou une sauce base", "Avoir des oeufs durs prêts"],
    nutrition: "Préparer à l'avance ne signifie pas cuisiner pendant 3 heures. 30-45 min le dimanche suffisent pour sécuriser 2-3 repas de semaine.",
    nutritionDetail: [
      "Exemple minimal : cuire 200g de riz complet, rôtir des légumes, cuire 4 oeufs durs.",
      "Une soupe préparée le dimanche = 3 repas du soir sans effort.",
      "Batch cooking partiel : cuisinez les bases, assemblez selon l'envie du moment.",
      "Conservez au frigo 3-4 jours max. Congelez si besoin pour la semaine suivante.",
    ],
    activity: "Maintenez vos 3 marches. Ajoutez une séance de renforcement léger si vous souhaitez progresser.",
    activityDetail: [
      "2 séances de renforcement musculaire léger (20 min) si vous souhaitez progresser.",
      "Continuez la marche quotidienne.",
    ],
    checklist: ["2 repas préparés d'avance", "Céréales cuites en quantité", "Soupe ou sauce de base préparée", "Oeufs durs disponibles", "Dimanche organisé"],
    tip: "30 min de préparation le dimanche = 5 décisions alimentaires de moins dans la semaine.",
  },
  {
    num: 9, title: "Manger plus lentement",
    objective: "Développer la pleine conscience alimentaire",
    color: 'from-purple-50 to-primary/5',
    habits: ["Poser la fourchette entre chaque bouchée", "Mâcher 15-20 fois chaque bouchée", "Repas minimum 20 minutes", "S'arrêter à 80% de satiété"],
    nutrition: "Manger vite est l'une des principales causes de suralimentation. La satiété met 20 minutes à arriver au cerveau. Si vous finissez en 10 min, vous ratez l'information.",
    nutritionDetail: [
      "Posez votre fourchette entre chaque bouchée : simple, efficace, difficile au début.",
      "Mâchez lentement : la digestion commence dans la bouche (enzymes salivaires).",
      "S'arrêter à 80% de satiété : vous n'avez pas besoin d'être 'plein'. Juste rassasié.",
      "Les repas pris en pleine conscience sont plus satisfaisants, même avec moins de quantité.",
    ],
    activity: "Marche après au moins 1 repas par jour.",
    activityDetail: [
      "La marche post-repas renforce la pleine conscience alimentaire.",
      "Le mouvement doux après le repas améliore la digestion.",
    ],
    checklist: ["Fourchette posée entre les bouchées", "Repas > 20 minutes", "Satiété à 80% respectée", "1 repas sans distraction", "Digestion observée"],
    tip: "Vous n'avez pas besoin de manger moins pour peser moins. Manger plus lentement suffit souvent.",
  },
  {
    num: 10, title: "Adapter les portions",
    objective: "Calibrer ses portions sans peser ni compter",
    color: 'from-rose-50 to-secondary/5',
    habits: ["Méthode assiette : ½ légumes, ¼ protéines, ¼ féculents", "Utiliser une assiette normale (pas un plat)", "Se resservir seulement après 10 minutes", "Écouter la fin de faim plutôt que la fin d'assiette"],
    nutrition: "Pas besoin de peser ses aliments. La méthode assiette donne une structure simple et efficace pour calibrer sans obsession.",
    nutritionDetail: [
      "Moitié de l'assiette : légumes (crus, cuits, chauds, froids).",
      "Un quart : protéines (viande, poisson, oeufs, légumineuses).",
      "Un quart : féculents (riz complet, pâtes, pain, légumineuses).",
      "Ne remplissez pas l'assiette 'parce qu'il reste du plat'. Servez ce qui semble raisonnable.",
    ],
    activity: "2-3 séances de sport (marche rapide, renforcement ou natation).",
    activityDetail: [
      "À ce stade du programme, les habitudes sont installées.",
      "Le sport renforce naturellement les bons comportements alimentaires.",
    ],
    checklist: ["Méthode assiette appliquée", "Assiette normale utilisée", "Pas de resservi immédiat", "Fin de faim écoutée", "Satisfaction observée"],
    tip: "L'assiette équilibrée n'est pas un régime. C'est un outil visuel pour manger bien sans compter.",
  },
  {
    num: 11, title: "Gérer les repas extérieurs",
    objective: "Manger à l'extérieur sans culpabilité ni déviation totale",
    color: 'from-amber-50 to-secondary/5',
    habits: ["Regarder le menu à l'avance si possible", "Choisir des plats avec légumes et protéines", "Manger lentement au restaurant", "Ne pas se priver totalement : choisir consciemment"],
    nutrition: "Manger au restaurant ne signifie pas 'tout gâcher'. C'est une occasion de profiter sans anxiété, en gardant quelques repères simples.",
    nutritionDetail: [
      "Au restaurant : privilégiez les plats avec légumes visibles et une protéine principale.",
      "Évitez les entrées + plat + dessert systématiques. Choisissez ce dont vous avez vraiment envie.",
      "Sauces et assaisonnements : demandez-les à part si possible.",
      "Un repas 'moins équilibré' ne ruine pas 11 semaines d'effort. La régularité prime.",
    ],
    activity: "Maintenez votre routine sportive. Les repas extérieurs ne doivent pas déclencher de compensation sportive.",
    activityDetail: [
      "Ne compensez pas un repas au restaurant par 2h de sport. Ce n'est pas sain mentalement.",
      "Continuez votre routine normale.",
    ],
    checklist: ["Menu regardé à l'avance", "Légumes et protéines prioritaires", "Sauce demandée à part", "Pas de culpabilité", "Repas suivant normal"],
    tip: "1 repas sur 21 dans la semaine ne change rien si les 20 autres sont équilibrés.",
  },
  {
    num: 12, title: "Bilan et autonomie",
    objective: "Évaluer les progrès et devenir autonome",
    color: 'from-green-50 to-secondary/5',
    habits: ["Relire le journal de la semaine 1", "Lister les habitudes installées", "Identifier les 2-3 habitudes à consolider", "Planifier la suite"],
    nutrition: "Ce programme n'est pas une fin. C'est le début d'une nouvelle façon de manger. Évaluez ce qui a changé et planifiez comment maintenir ces nouvelles habitudes.",
    nutritionDetail: [
      "Comparez votre alimentation actuelle avec celle de la semaine 1 : les différences sont réelles.",
      "Identifiez les 3 habitudes qui ont eu le plus d'impact pour vous.",
      "Planifiez les prochaines semaines en autonomie avec ces habitudes comme base.",
      "Si vous avez besoin d'un accompagnement, c'est le bon moment pour consulter.",
    ],
    activity: "Continuez votre routine. Le sport est maintenant une habitude, pas une contrainte.",
    activityDetail: [
      "Célébrez les 12 semaines. C'est une vraie réussite.",
      "Maintenez le rythme sportif établi.",
      "Explorez de nouvelles activités si vous avez envie de progresser.",
    ],
    checklist: ["Bilan de la semaine 1 relu", "Habitudes listées", "Progrès mesurés", "Plan de maintien défini", "Fierté autorisée"],
    tip: "12 semaines pour changer des habitudes de toute une vie. C'est rapide, en fait.",
  },
];

export const REEQUILIBRAGE_DAY_PLANS = [
  {
    id: 'a', label: 'Journée A — Classique',
    subtitle: 'La journée type équilibrée du programme',
    totalKcal: 1990,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 380, items: ["Porridge 50g avoine + 200ml lait végétal", '1 banane + 1 c.à.c. beurre amande', '1 yaourt grec nature', 'Café ou thé sans sucre'], alt: '2 oeufs brouillés + 2 tranches pain complet + 1 orange' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 580, items: ['130g poulet grillé aux herbes', '80g riz basmati ou quinoa', 'Salade verte + tomates cerises + concombre', 'Vinaigrette légère huile olive'], alt: 'Bowl quinoa avocat œuf poché + légumes variés' },
      { time: '16h00', name: 'Collation (si faim)', icon: '🍎', kcal: 170, items: ['1 pomme ou poire', '15g amandes ou noix'], alt: 'Fromage blanc 0% + 1 c.à.c. miel + fruits' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 500, items: ['120g filet de poisson vapeur ou grillé', 'Légumes rôtis en quantité (courgettes, poivrons, carottes)', '60g féculents optionnel (patate douce)', '1 yaourt nature'], alt: 'Omelette 3 oeufs + légumes + salade verte' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['1,5 à 2 L eau plate', 'Thé vert ou infusion', 'Café max 2/jour sans sucre'], alt: 'Eau pétillante si envie de bulles' },
    ],
  },
  {
    id: 'b', label: 'Journée B — Végétarienne',
    subtitle: '100% végétarien, complet et savoureux',
    totalKcal: 1960,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 360, items: ['2 tranches pain complet + avocat écrasé', '2 oeufs pochés', 'Tomates cerises', 'Café ou thé'], alt: 'Skyr 200g + granola + fruits rouges + noix' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 540, items: ['Curry pois chiches légumes (200g pois chiches)', 'Riz complet 80g', 'Yaourt nature en accompagnement'], alt: 'Salade lentilles feta tomates herbes' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 180, items: ['200g fromage blanc 0%', '1 c.à.s. graines de chia', 'Fruits rouges'], alt: 'Houmous + crudités (carottes, concombre)' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 480, items: ['Omelette 3 oeufs aux légumes variés', 'Salade verte + vinaigrette', '1 tranche pain complet', '1 fromage blanc'], alt: 'Soupe lentilles corail + pain complet + yaourt' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['1,5 à 2 L eau', 'Thé vert 2-3 tasses', 'Infusion le soir'], alt: '' },
    ],
  },
  {
    id: 'c', label: 'Journée C — Familiale',
    subtitle: 'Des repas qui plaisent à toute la famille',
    totalKcal: 2020,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 400, items: ['Pancakes avoine banane (3 petits)', 'Compote maison pomme cannelle', '1 yaourt grec', 'Café ou thé'], alt: "Céréales complètes + lait + fruit frais" },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 600, items: ['Poulet basquaise léger (130g poulet)', 'Couscous 80g', 'Légumes cuisinés dans la sauce', '1 yaourt'], alt: 'Poêlée riz légumes tofu ou poulet' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 160, items: ['1 fruit de saison', '1 tranche pain complet + beurre amande'], alt: 'Compote sans sucre ajouté + biscuits maison' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 500, items: ['Gratin courgettes pommes de terre léger', 'Salade verte', '1 yaourt ou fromage blanc'], alt: 'Chili végétarien + pain complet' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['Eau pour toute la famille', 'Pas de sodas à table', 'Eau aromatisée maison (citron, menthe)'], alt: '' },
    ],
  },
  {
    id: 'd', label: 'Journée D — Rapide',
    subtitle: 'Tout prêt en moins de 15 min par repas',
    totalKcal: 1970,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 350, items: ["Yaourt grec 200g + muesli 30g + fruits", 'Café ou thé'], alt: 'Pain complet + fromage + fruit' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 520, items: ['Wrap poulet crudités sauce yaourt', '1 banane ou fruit', '1 yaourt'], alt: 'Tartines pain complet saumon avocat + salade' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 150, items: ['1 fruit', '1 poignée amandes'], alt: 'Fromage blanc + miel' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 520, items: ['Pâtes complètes sauce tomate thon (10 min)', 'Salade verte', '1 fromage blanc'], alt: 'Bol riz légumes œuf au plat (15 min)' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['Bouteille eau à emporter', 'Café ou thé sans sucre'], alt: '' },
    ],
  },
];

export const REEQUILIBRAGE_RECIPES = [
  {
    id: 'r1', title: 'Assiette Poulet Riz Légumes',
    description: 'Le repas équilibré par excellence : protéines, glucides complexes et légumes en quantité.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 20, calories: 480, proteins: 38, carbs: 45, fats: 12, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600',
    ingredients: ['130g blanc de poulet', '80g riz basmati', '1 courgette', '1 poivron', 'Herbes de Provence', "Huile d'olive", 'Sel, poivre'],
    steps: ['Cuire le riz basmati 12 min.', 'Griller le poulet aux herbes 10 min.', 'Poêler courgette et poivron 5 min.', 'Assembler dans une assiette et servir.'],
    dietitian_tips: 'Le riz basmati a un IG plus bas que le riz blanc classique. Idéal pour une énergie stable.',
  },
  {
    id: 'r2', title: 'Pâtes Complètes Sauce Tomate Thon',
    description: 'Un plat rapide, économique et équilibré. Prêt en 15 minutes.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 5, cook_time: 12, calories: 460, proteins: 30, carbs: 56, fats: 8, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600',
    ingredients: ['200g pâtes complètes', '1 boîte tomates pelées', '1 boîte thon au naturel', '1 oignon', '2 gousses ail', 'Basilic', "Huile d'olive"],
    steps: ['Cuire les pâtes al dente.', 'Faire revenir oignon et ail.', 'Ajouter tomates, mijoter 8 min.', 'Incorporer le thon.', 'Mélanger avec les pâtes et le basilic.'],
    dietitian_tips: 'Les pâtes complètes ont un IG de 40 vs 70 pour les blanches. Même plaisir, meilleure énergie.',
    meal_prep: true,
  },
  {
    id: 'r3', title: 'Bowl Quinoa Avocat Oeuf',
    description: 'Un bowl coloré et complet, riche en bonnes graisses et protéines végétales.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 15, calories: 490, proteins: 22, carbs: 48, fats: 22, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    ingredients: ['80g quinoa', '2 oeufs', '1/2 avocat', 'Roquette', 'Tomates cerises', 'Jus de citron', "Huile d'olive"],
    steps: ['Cuire le quinoa 15 min.', 'Pocher les oeufs 3 min.', 'Couper avocat et tomates.', 'Assembler le bowl, assaisonner.'],
    dietitian_tips: "Le quinoa est une protéine complète. L'avocat apporte des acides gras mono-insaturés bénéfiques.",
  },
  {
    id: 'r4', title: 'Curry de Pois Chiches Légumes',
    description: 'Un curry végétarien réconfortant, riche en fibres et protéines végétales.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 20, calories: 420, proteins: 16, carbs: 52, fats: 12, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    ingredients: ['400g pois chiches cuits', '1 courgette', '1 poivron', '200ml lait de coco light', '1 c.à.s. curry', '1 oignon', 'Ail', 'Coriandre'],
    steps: ['Faire revenir oignon et ail avec le curry.', 'Ajouter les légumes, cuire 5 min.', 'Incorporer pois chiches et lait de coco.', 'Mijoter 10 min. Servir avec coriandre.'],
    dietitian_tips: 'Les pois chiches fournissent 8g de protéines pour 100g avec des fibres rassasiantes.',
    meal_prep: true,
  },
  {
    id: 'r5', title: 'Gratin Léger Courgettes Pommes de Terre',
    description: 'Un gratin familial allégé, sans béchamel lourde. Réconfortant et sain.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 15, cook_time: 35, calories: 320, proteins: 12, carbs: 38, fats: 10, servings: 4, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600',
    ingredients: ['3 courgettes', '4 pommes de terre moyennes', '2 oeufs', '100ml yaourt grec', '50g gruyère râpé', 'Ail', 'Herbes de Provence'],
    steps: ['Préchauffer à 180°C.', 'Couper légumes en fines rondelles.', 'Mélanger oeufs, yaourt, ail, sel.', 'Alterner légumes dans un plat.', 'Verser le mélange, parsemer de gruyère.', 'Cuire 35 min.'],
    dietitian_tips: 'Le yaourt remplace la crème fraîche pour une version légère mais toujours crémeuse.',
    meal_prep: true,
  },
  {
    id: 'r6', title: 'Salade Composée Oeuf Lentilles',
    description: 'Une salade repas complète et rassasiante, parfaite pour le déjeuner.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 10, calories: 380, proteins: 24, carbs: 32, fats: 14, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600',
    ingredients: ['200g lentilles vertes cuites', '2 oeufs durs', 'Salade verte', 'Tomates', 'Vinaigrette moutarde', 'Herbes fraîches'],
    steps: ['Cuire les oeufs durs 10 min.', 'Préparer la vinaigrette.', 'Dresser la salade avec lentilles, oeufs coupés.', 'Assaisonner et servir.'],
    dietitian_tips: 'Les lentilles vertes sont riches en fer, fibres et protéines. La combinaison oeuf + lentilles = protéines complètes.',
  },
  {
    id: 'r7', title: 'Tartines Complètes Avocat Saumon',
    description: 'Un déjeuner ou petit-déjeuner sophistiqué, riche en oméga-3.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 5, cook_time: 0, calories: 380, proteins: 22, carbs: 28, fats: 18, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600',
    ingredients: ['2 tranches pain complet', '1/2 avocat', '60g saumon fumé', 'Citron', 'Ciboulette', 'Poivre'],
    steps: ["Griller légèrement le pain.", "Écraser l'avocat avec citron et sel.", 'Disposer le saumon fumé.', 'Parsemer de ciboulette et poivre.'],
    dietitian_tips: "Le saumon fumé apporte des oméga-3 EPA/DHA bénéfiques pour le coeur et le cerveau.",
  },
  {
    id: 'r8', title: 'Porridge Pomme Cannelle',
    description: "Un petit-déjeuner chaud et réconfortant, naturellement sucré par la pomme.",
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 5, cook_time: 5, calories: 350, proteins: 12, carbs: 52, fats: 8, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1571748982800-fa51082c2224?w=600',
    ingredients: ["50g flocons d'avoine", '200ml lait végétal', '1 pomme', '1 c.à.c. cannelle', '1 c.à.s. beurre amande', '1 yaourt grec'],
    steps: ["Chauffer le lait, ajouter les flocons.", "Cuire 5 min en remuant.", "Râper ou couper la pomme.", "Garnir avec pomme, cannelle et beurre amande."],
    dietitian_tips: "La cannelle aide à réguler la glycémie. L'avoine est la céréale avec le meilleur indice de satiété.",
  },
  {
    id: 'r9', title: 'Yaourt Grec Fruits Noix',
    description: "Un petit-déjeuner ou collation express, prêt en 2 minutes.",
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 2, cook_time: 0, calories: 280, proteins: 18, carbs: 24, fats: 12, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600',
    ingredients: ['200g yaourt grec nature', '80g fruits frais de saison', '20g noix ou amandes', '1 c.à.c. miel optionnel'],
    steps: ["Verser le yaourt dans un bol.", "Ajouter les fruits coupés.", "Parsemer de noix.", "Ajouter le miel si désiré."],
    dietitian_tips: "Le yaourt grec contient 2x plus de protéines que le yaourt classique. Excellent pour tenir jusqu'au déjeuner.",
  },
  {
    id: 'r10', title: 'Soupe Complète Lentilles Corail',
    description: 'Une soupe repas épaisse et réconfortante, ultra-protéinée et végétarienne.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 25, calories: 350, proteins: 18, carbs: 48, fats: 6, servings: 3, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600',
    ingredients: ['200g lentilles corail', '1 oignon', '2 carottes', '1 c.à.s. cumin', '1 c.à.c. curcuma', 'Bouillon de légumes', 'Jus de citron'],
    steps: ['Faire revenir oignon avec les épices.', 'Ajouter carottes et lentilles.', "Couvrir de bouillon, cuire 20 min.", 'Mixer partiellement.', 'Servir avec un filet de citron.'],
    dietitian_tips: 'Les lentilles corail ne nécessitent pas de trempage. Riches en protéines et très faciles à digérer.',
    meal_prep: true,
  },
  {
    id: 'r11', title: 'Wrap Poulet Crudités',
    description: 'Un lunch express pratique à emporter, équilibré et savoureux.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 0, calories: 420, proteins: 32, carbs: 36, fats: 12, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600',
    ingredients: ['1 tortilla complète', '100g poulet cuit émincé', '1/2 avocat', 'Roquette', 'Tomate', '2 c.à.s. fromage blanc 0%', 'Moutarde', 'Citron'],
    steps: ['Préparer la sauce fromage blanc + moutarde + citron.', 'Tartiner la tortilla.', 'Disposer poulet, avocat, roquette, tomate.', 'Rouler et déguster.'],
    dietitian_tips: 'Préférez les tortillas 100% blé complet pour plus de fibres.',
    meal_prep: true,
  },
  {
    id: 'r12', title: 'Poêlée Riz Légumes Tofu',
    description: 'Une poêlée asiatique légère, végétarienne et rassasiante.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 15, calories: 430, proteins: 20, carbs: 52, fats: 12, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=600',
    ingredients: ['150g tofu ferme', '150g riz complet cuit', '1 poivron', '1 carotte', 'Sauce soja', 'Huile sésame', 'Gingembre', 'Oignon vert'],
    steps: ['Couper le tofu en dés, poêler 4 min.', 'Faire sauter les légumes.', 'Ajouter le riz et mélanger.', 'Assaisonner sauce soja et huile sésame.'],
    dietitian_tips: 'Le tofu ferme contient 15g de protéines/100g et absorbe parfaitement les saveurs asiatiques.',
  },
  {
    id: 'r13', title: 'Omelette Légumes Fromage Frais',
    description: 'Une omelette moelleuse et crémeuse, prête en 10 minutes.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 5, cook_time: 8, calories: 310, proteins: 22, carbs: 8, fats: 20, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600',
    ingredients: ['3 oeufs', '50g fromage frais léger', 'Poivron', 'Champignons', 'Épinards', 'Ciboulette', "Huile d'olive"],
    steps: ['Faire revenir les légumes 3 min.', 'Battre les oeufs, assaisonner.', 'Verser sur les légumes.', 'Ajouter le fromage frais, plier et servir.'],
    dietitian_tips: 'Le fromage frais allège la texture sans ajouter beaucoup de calories. Excellent substitut à la crème.',
  },
  {
    id: 'r14', title: 'Chili Végétarien',
    description: 'Un chili généreux et réconfortant, sans viande mais avec beaucoup de saveur.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 30, calories: 380, proteins: 16, carbs: 52, fats: 8, servings: 3, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600',
    ingredients: ['400g haricots rouges', '400g pois chiches', '1 boîte tomates', '1 oignon', '1 poivron', '1 c.à.s. cumin', 'Piment doux', 'Coriandre'],
    steps: ['Faire revenir oignon et poivron.', 'Ajouter épices, tomates et légumineuses.', 'Mijoter 20 min.', 'Servir avec coriandre fraîche.'],
    dietitian_tips: 'Ce chili se conserve 5 jours et se congèle parfaitement. Idéal pour le meal prep.',
    meal_prep: true,
  },
  {
    id: 'r15', title: 'Filet de Poisson Légumes Vapeur',
    description: 'Une assiette légère, complète et facile à digérer.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 5, cook_time: 15, calories: 320, proteins: 32, carbs: 22, fats: 6, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600',
    ingredients: ['150g filet cabillaud ou lieu noir', 'Brocoli', 'Carottes', 'Haricots verts', 'Citron', 'Herbes', 'Huile olive'],
    steps: ['Cuire les légumes vapeur 10 min.', 'Cuire le poisson vapeur ou poêlé 5-6 min.', 'Assaisonner huile olive et citron.'],
    dietitian_tips: 'Le poisson blanc est la protéine la plus légère. Moins de 100 kcal/100g avec 20g de protéines.',
  },
  {
    id: 'r16', title: 'Poulet Basquaise Léger',
    description: 'Un grand classique familial revisité en version plus légère et colorée.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 15, cook_time: 35, calories: 450, proteins: 38, carbs: 28, fats: 16, servings: 4, difficulty: 'moyen',
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600',
    ingredients: ['4 cuisses de poulet (sans peau)', '3 poivrons variés', '2 oignons', '400g tomates pelées', '2 gousses ail', 'Thym, laurier', 'Piment d\'Espelette'],
    steps: ['Faire dorer le poulet sans peau.', 'Faire revenir oignons et poivrons.', 'Ajouter tomates, ail, épices.', 'Remettre le poulet, mijoter 25 min.'],
    dietitian_tips: 'Retirer la peau du poulet réduit les lipides de 40%. La sauce légumineuse apporte fibres et vitamines.',
    meal_prep: true,
  },
  {
    id: 'r17', title: 'Couscous Légumes Pois Chiches',
    description: 'Un couscous généreux, végétarien ou avec protéine selon vos envies.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 15, cook_time: 25, calories: 480, proteins: 18, carbs: 68, fats: 10, servings: 4, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    ingredients: ['200g semoule complète', '400g pois chiches', 'Carottes, courgettes, navets', '1 boîte tomates', 'Ras el hanout', 'Oignon', 'Bouillon'],
    steps: ['Faire revenir oignon avec les épices.', 'Ajouter légumes et bouillon.', 'Mijoter 20 min.', 'Incorporer pois chiches.', 'Préparer la semoule, servir ensemble.'],
    dietitian_tips: 'La semoule complète a un IG plus bas que la semoule blanche. Le couscous est un plat très rassasiant.',
    meal_prep: true,
  },
  {
    id: 'r18', title: 'Salade Grecque Complète',
    description: 'La salade grecque classique transformée en repas complet avec des protéines.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 0, calories: 380, proteins: 16, carbs: 24, fats: 22, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600',
    ingredients: ['Tomates', 'Concombre', 'Poivron', 'Olives', '100g feta', '1 boîte pois chiches', 'Oignon rouge', 'Huile olive', 'Origan'],
    steps: ['Couper tous les légumes.', 'Ajouter pois chiches égouttés.', 'Émietter la feta.', 'Assaisonner et parsemer d\'origan.'],
    dietitian_tips: "Les olives et l'huile d'olive sont des graisses monoinsaturées excellentes pour la santé cardiovasculaire.",
  },
  {
    id: 'r19', title: 'Dhal Lentilles Corail',
    description: 'Le grand classique indien : crémeux, épicé et ultra-nutritif.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 20, calories: 390, proteins: 18, carbs: 52, fats: 10, servings: 3, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    ingredients: ['200g lentilles corail', '1 oignon', '2 gousses ail', '1 c.à.c. curcuma', '1 c.à.c. cumin', '1 c.à.c. gingembre', '200ml lait de coco light', 'Coriandre'],
    steps: ['Faire revenir oignon, ail, épices.', 'Ajouter lentilles et eau.', 'Cuire 15 min.', 'Incorporer lait de coco.', 'Servir avec coriandre fraîche.'],
    dietitian_tips: 'Le curcuma est anti-inflammatoire. Les lentilles corail cuisent en 15 min sans trempage.',
    meal_prep: true,
  },
  {
    id: 'r20', title: 'Patate Douce Farcie',
    description: 'Une patate douce généreuse garnie de légumineuses et légumes.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 40, calories: 420, proteins: 14, carbs: 62, fats: 10, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1604908177453-7462950a6a3b?w=600',
    ingredients: ['2 grosses patates douces', '200g pois chiches', 'Épinards', 'Fromage frais léger', 'Cumin', 'Paprika', 'Ail', 'Citron'],
    steps: ['Cuire les patates au four 35-40 min à 200°C.', 'Mélanger pois chiches, épinards, fromage frais, épices.', 'Couper les patates en deux.', 'Farcir et servir.'],
    dietitian_tips: "La patate douce a un IG de 44 vs 78 pour la pomme de terre. Riche en bêta-carotène.",
    meal_prep: true,
  },
  {
    id: 'r21', title: 'Pancakes Avoine Banane',
    description: 'Des pancakes moelleux et naturellement sucrés, sans farine blanche ni sucre ajouté.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 5, cook_time: 10, calories: 330, proteins: 16, carbs: 42, fats: 8, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600',
    ingredients: ['1 banane mûre', '2 oeufs', "40g flocons d'avoine mixés", '1/2 c.à.c. levure', 'Cannelle', '1 c.à.c. huile coco'],
    steps: ['Écraser la banane.', 'Mélanger avec oeufs, avoine, levure, cannelle.', 'Cuire en petits disques 2 min/côté.', 'Servir avec yaourt grec et fruits.'],
    dietitian_tips: 'La banane mûre sucre naturellement. Excellente source d\'énergie pour la matinée sans pic glycémique excessif.',
  },
  {
    id: 'r22', title: 'Compote Maison Fromage Blanc',
    description: 'Un dessert ou collation simple, fait maison, sans sucre ajouté.',
    category: 'collation', meal_category: 'collation',
    prep_time: 5, cook_time: 15, calories: 200, proteins: 12, carbs: 28, fats: 2, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600',
    ingredients: ['4 pommes', '1 c.à.c. cannelle', 'Un peu d\'eau', '200g fromage blanc 0%', '1 c.à.c. miel optionnel'],
    steps: ['Peler et couper les pommes.', 'Cuire 15 min avec cannelle et un peu d\'eau.', 'Écraser à la fourchette (pas de mixeur).', 'Servir tiède avec le fromage blanc.'],
    dietitian_tips: 'La compote maison contient 0g de sucre ajouté vs 15g dans les compotes industrielles. La cannelle régule la glycémie.',
  },
];

export const REEQUILIBRAGE_SHOPPING = [
  { cat: 'Légumes 🥦', items: ['Courgettes (3)', 'Poivrons variés (4)', 'Épinards frais (200g)', 'Salade verte (2)', 'Tomates cerises (250g)', 'Concombres (2)', 'Carottes (4)', 'Brocoli (1)', 'Champignons (200g)', 'Haricots verts (300g)'] },
  { cat: 'Fruits 🍎', items: ['Bananes (5)', 'Pommes (5)', 'Kiwis (4)', 'Fruits rouges surgelés (300g)', 'Citrons (3)', 'Fruits de saison (selon arrivage)'] },
  { cat: 'Protéines animales 🥩', items: ['Blanc de poulet (400g)', 'Filet de poisson blanc (300g)', 'Saumon fumé (100g)', 'Oeufs (12)', 'Thon au naturel (3 boîtes)'] },
  { cat: 'Protéines végétales 🌱', items: ['Pois chiches cuits (2 boîtes)', 'Lentilles vertes cuites (2 boîtes)', 'Lentilles corail sèches (300g)', 'Haricots rouges cuits (1 boîte)', 'Tofu ferme (200g)'] },
  { cat: 'Féculents 🌾', items: ['Riz basmati ou complet (500g)', 'Pâtes complètes (500g)', "Flocons d'avoine (500g)", 'Quinoa (300g)', 'Pain complet (1 paquet)', 'Semoule complète (300g)', 'Patate douce (3)'] },
  { cat: 'Produits laitiers 🥛', items: ['Yaourt grec nature (6)', 'Fromage blanc 0% (2 x 500g)', 'Fromage frais léger (150g)', 'Lait végétal non sucré (1L)'] },
  { cat: 'Épicerie 🫙', items: ["Huile d'olive extra vierge", 'Moutarde', 'Sauce soja', 'Curcuma, cumin, curry', 'Cannelle', 'Herbes de Provence', 'Bouillon de légumes', 'Vinaigre balsamique', 'Lait de coco light'] },
  { cat: 'Petits plaisirs raisonnables 🍫', items: ['Chocolat noir 70% (100g)', 'Miel (1 pot)', 'Noix et amandes (200g)', 'Beurre amande (1 pot)', 'Muesli sans sucre (300g)'] },
];

export const REEQUILIBRAGE_PRATIQUE = [
  {
    icon: '🍽️', title: "Composer une assiette équilibrée",
    desc: "La règle simple des 3 tiers pour chaque repas principal.",
    detail: {
      intro: "L'assiette équilibrée est l'outil le plus simple et le plus efficace pour manger bien sans compter les calories. Il suffit de respecter 3 zones visuelles.",
      points: [
        "Moitié de l'assiette : légumes (crus, cuits, chauds, froids — tous comptent).",
        "Un quart : protéines (viande, poisson, oeufs, légumineuses, fromage).",
        "Un quart : féculents (riz, pâtes, pain, légumineuses — de préférence complets).",
        "Un filet d'huile olive ou quelques noix pour les bonnes graisses.",
        "Un produit laitier ou un fruit en fin de repas.",
        "Pas besoin de peser : utilisez votre assiette normale comme repère visuel.",
      ],
      example: "Exemple : salade verte + tomates (½ assiette) + poulet grillé (¼) + riz complet (¼) + filet d'huile olive = assiette parfaitement équilibrée.",
      tip: "Si chaque repas ressemble à ça 80% du temps, vous n'avez pas besoin de compter quoi que ce soit.",
    },
  },
  {
    icon: '🍴', title: "Gérer un restaurant",
    desc: "Manger dehors sans anxiété ni culpabilité.",
    detail: {
      intro: "Les repas au restaurant font partie de la vie sociale et du plaisir. Les appréhender avec anxiété ruine à la fois le plaisir et la santé. Quelques repères simples suffisent.",
      points: [
        "Regardez le menu à l'avance si possible (sur le site du restaurant).",
        "Choisissez un plat avec une protéine visible et des légumes.",
        "Demandez les sauces à part si vous le souhaitez.",
        "Évitez l'entrée + plat + dessert systématique. Choisissez ce dont vous avez vraiment envie.",
        "Mangez lentement, appréciez le moment. C'est un plaisir, pas une faute.",
        "Le repas suivant sera normal. Pas de restriction compensatoire.",
      ],
      example: "Au restaurant : salade composée (entrée légère) + plat principal avec protéine et légumes + dessert si envie réelle, pas par automatisme.",
      tip: "Un repas sur 21 dans la semaine ne change rien si les 20 autres sont équilibrés. Profitez.",
    },
  },
  {
    icon: '🍫', title: "Gérer une envie de sucre",
    desc: "Comprendre l'envie avant de la subir.",
    detail: {
      intro: "Une envie de sucre n'est pas un manque de volonté. C'est un signal à décoder. Comprendre pourquoi l'envie arrive change complètement la façon d'y répondre.",
      points: [
        "Buvez un grand verre d'eau et attendez 5 minutes. Beaucoup d'envies disparaissent.",
        "Identifiez la cause : faim réelle, stress, ennui, habitude, manque de sommeil ?",
        "Si faim réelle : mangez un vrai repas ou une collation protéinée.",
        "Si envie après repas : le repas manquait probablement de fibres ou de protéines.",
        "Si envie émotionnelle : identifiez l'émotion et trouvez une autre réponse (marche, appel, musique).",
        "Si envie persistante : autorisez 2 carreaux de chocolat noir 70%+. C'est mieux que de craquer sur des biscuits industriels.",
      ],
      example: "Envie de sucre à 16h : d'abord un verre d'eau. Toujours présente ? 1 pomme + 15g amandes = 10g de sucre naturel + fibres + protéines. Satisfaisant.",
      tip: "Interdire le sucre rend l'envie plus forte. Mieux vaut choisir consciemment un petit plaisir de qualité.",
    },
  },
  {
    icon: '📅', title: "Anticiper une semaine chargée",
    desc: "Ne pas laisser le manque de temps décider pour vous.",
    detail: {
      intro: "Les semaines chargées sont les moments où l'alimentation déraille le plus. Pas par manque de motivation, mais par manque d'organisation. Quelques minutes de préparation le week-end changent tout.",
      points: [
        "Le dimanche soir : préparez 2-3 repas de base (riz, lentilles, légumes rôtis, soupe).",
        "Préparez des lunch boxes pour 2-3 jours d'avance.",
        "Ayez toujours en stock : oeufs, légumineuses en boîte, légumes surgelés.",
        "Si vous n'avez vraiment pas le temps : un repas simple mais équilibré (omelette + salade) vaut mieux que de sauter le repas.",
        "Les applications de livraison peuvent être utiles si vous choisissez bien (salades, poisson, légumes).",
        "Gardez des collations saines dans votre sac ou bureau.",
      ],
      example: "Dimanche 45 min : cuire 300g de riz complet, rôtir une plaque de légumes, cuire 4 oeufs durs, préparer une soupe de lentilles. Résultat : 8-10 repas sécurisés.",
      tip: "L'improvisation alimentaire conduit toujours aux mêmes choix : fast-food, grignotage, repas sautés. L'organisation est la solution.",
    },
  },
  {
    icon: '⚖️', title: 'Éviter le "tout ou rien"',
    desc: "Le perfectionnisme alimentaire sabote plus qu'il n'aide.",
    detail: {
      intro: "Le 'tout ou rien' est le piège le plus courant en rééquilibrage alimentaire : un écart = tout est gâché = autant continuer à mal manger. Cette logique est fausse et destructrice.",
      points: [
        "Un repas déséquilibré sur 21 dans la semaine = moins de 5% de vos repas. Aucun impact réel.",
        "Ce qui compte c'est la tendance sur plusieurs semaines, pas le repas ponctuel.",
        "Après un repas 'de plaisir' : le repas suivant est simplement normal, sans restriction.",
        "La flexibilité est une compétence à développer, pas un échec.",
        "Les régimes stricts échouent à 95% à long terme. La flexibilité réussit.",
        "Apprenez à apprécier les 'exceptions' sans culpabilité ni compensation.",
      ],
      example: "Dîner de fête avec dessert et vin : lendemain matin, petit-déjeuner normal. Pas de jeûne, pas de sport intense, pas de restriction. Juste la routine habituelle.",
      tip: "La santé se construit repas après repas sur des années. Un seul repas ne peut ni tout gâcher, ni tout réparer.",
    },
  },
];