export const WEEKS = [
  {
    num: 1,
    title: 'Mise en place',
    objective: 'Installer les bases sans restriction brutale.',
    color: 'from-primary/5 to-transparent',
    habits: ['Preparer 2 sources de proteines', 'Boire 1,5 a 2 L d eau', 'Marcher 20 minutes par jour'],
    nutrition: 'Priorite aux repas simples, proteines a chaque repas et legumes en volume.',
    nutritionDetail: ['Garder une portion de feculents le matin ou le midi', 'Limiter les boissons sucrees', 'Prevoir une collation proteinee si besoin'],
    activity: 'Reprendre doucement avec marche et mobilite.',
    activityDetail: ['2 seances courtes de renforcement', 'Objectif 7 000 pas par jour', 'Sommeil regulier'],
    checklist: ['Courses faites', '2 repas prepares', 'Eau suivie'],
    tip: 'Le but de la premiere semaine est la regularite, pas la perfection.',
  },
  {
    num: 2,
    title: 'Rythme regulier',
    objective: 'Stabiliser les repas et reduire les ecarts non prevus.',
    color: 'from-secondary/5 to-transparent',
    habits: ['Composer une assiette type', 'Planifier 4 diners', 'Ajouter des legumes midi et soir'],
    nutrition: 'Assiette type : proteines, legumes, feculents ajustes, matiere grasse mesuree.',
    nutritionDetail: ['Viser une vraie source de proteines par repas', 'Choisir des feculents complets si possible', 'Garder un plaisir planifie dans la semaine'],
    activity: 'Augmenter progressivement la depense quotidienne.',
    activityDetail: ['2 a 3 seances de renforcement', '8 000 pas par jour', 'Etirements legers apres seance'],
    checklist: ['Assiette type', 'Legumes quotidiens', 'Pas suivis'],
    tip: 'Une seche durable fonctionne mieux avec un deficit modere.',
  },
  {
    num: 3,
    title: 'Proteines et satiete',
    objective: 'Mieux gerer la faim avec des repas rassasiants.',
    color: 'from-primary/5 to-transparent',
    habits: ['Ajouter une proteine au petit-dejeuner', 'Prevoir une collation utile', 'Manger lentement'],
    nutrition: 'Proteines et fibres deviennent les deux piliers de la semaine.',
    nutritionDetail: ['Skyr, oeufs, tofu, poisson, poulet ou legumes secs', 'Crudites ou legumes cuits a chaque repas', 'Fruits entiers plutot que jus'],
    activity: 'Conserver le renforcement pour proteger la masse musculaire.',
    activityDetail: ['3 mouvements de base par seance', 'Progression douce des charges', 'Repos si fatigue marquee'],
    checklist: ['Petit-dejeuner proteine', 'Fibres', 'Renforcement'],
    tip: 'Si la faim augmente trop, on ajuste les volumes avant de baisser les calories.',
  },
  {
    num: 4,
    title: 'Milieu de programme',
    objective: 'Evaluer les sensations et ajuster sans se durcir.',
    color: 'from-secondary/5 to-transparent',
    habits: ['Faire un bilan energie', 'Garder 1 repas flexible', 'Preparer les dejeuners'],
    nutrition: 'On verifie que le programme reste compatible avec la vraie vie.',
    nutritionDetail: ['Noter faim, sommeil et energie', 'Eviter de compenser un ecart par une restriction forte', 'Hydratation stable'],
    activity: 'Une semaine solide mais recuperable.',
    activityDetail: ['2 a 3 seances selon fatigue', 'Cardio doux optionnel', 'Priorite au sommeil'],
    checklist: ['Bilan fait', 'Lunch boxes', 'Sommeil'],
    tip: 'La progression vient de la moyenne de la semaine.',
  },
  {
    num: 5,
    title: 'Precision douce',
    objective: 'Ameliorer les portions sans compter obsessionnellement.',
    color: 'from-primary/5 to-transparent',
    habits: ['Mesurer les huiles', 'Preparer les collations', 'Garder un diner leger'],
    nutrition: 'On affine les apports les plus faciles a sous-estimer.',
    nutritionDetail: ['Huiles, noix et fromages en portions mesurees', 'Proteines maigres plus frequentes', 'Legumes a volonte selon tolerance'],
    activity: 'Maintenir le volume, eviter le surentrainement.',
    activityDetail: ['Renforcement regulier', 'Marche apres repas si possible', 'Jour off assume'],
    checklist: ['Portions ajustees', 'Collations pretes', 'Jour off'],
    tip: 'Un petit ajustement bien tenu vaut mieux qu une grande restriction impossible.',
  },
  {
    num: 6,
    title: 'Consolidation',
    objective: 'Rendre les automatismes plus naturels.',
    color: 'from-secondary/5 to-transparent',
    habits: ['Repeter les repas qui marchent', 'Anticiper les sorties', 'Suivre la progression'],
    nutrition: 'La simplicite devient un avantage.',
    nutritionDetail: ['Garder 3 repas favoris', 'Prevoir une option restaurant', 'Ne pas supprimer tous les glucides'],
    activity: 'Bouger souvent plutot que tout miser sur une grosse seance.',
    activityDetail: ['Objectif pas stable', 'Renforcement 2 a 3 fois', 'Mobilite 5 minutes'],
    checklist: ['Repas favoris', 'Sortie anticipee', 'Progression notee'],
    tip: 'Les automatismes reduisent la charge mentale.',
  },
  {
    num: 7,
    title: 'Derniere ligne droite',
    objective: 'Rester constant sans chercher l extreme.',
    color: 'from-primary/5 to-transparent',
    habits: ['Limiter le grignotage', 'Garder les repas complets', 'Proteger le sommeil'],
    nutrition: 'On reste sur le cadre, sans supprimer de famille alimentaire.',
    nutritionDetail: ['Collations seulement si faim reelle', 'Diners riches en legumes', 'Sel et hydratation coherents'],
    activity: 'Qualite de mouvement et recuperation.',
    activityDetail: ['Seances courtes mais propres', 'Marche quotidienne', 'Pas de punition sportive'],
    checklist: ['Grignotage maitrise', 'Diners complets', 'Recuperation'],
    tip: 'La fatigue peut monter : on ajuste, on ne force pas aveuglement.',
  },
  {
    num: 8,
    title: 'Sortie de seche',
    objective: 'Stabiliser les resultats et preparer la suite.',
    color: 'from-secondary/5 to-transparent',
    habits: ['Faire le bilan', 'Remonter legerement les apports si besoin', 'Choisir les habitudes a garder'],
    nutrition: 'La fin du programme sert a eviter le rebond.',
    nutritionDetail: ['Reintroduire progressivement plus de glucides si necessaire', 'Garder proteines et legumes', 'Conserver les repas reperes'],
    activity: 'Continuer une routine realiste.',
    activityDetail: ['2 seances minimum', 'Pas quotidiens', 'Objectif maintien'],
    checklist: ['Bilan', 'Habitudes choisies', 'Suite planifiee'],
    tip: 'Une bonne sortie de seche est aussi importante que la seche elle-meme.',
  },
];

export const DAY_PLANS = [
  {
    id: 'a',
    label: 'Standard',
    subtitle: 'Journee equilibree et simple',
    totalKcal: 1800,
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200',
    meals: [
      { icon: '🥣', name: 'Petit-dejeuner', time: '7h30', kcal: 420, items: ['Skyr ou fromage blanc', 'Flocons d avoine', 'Fruits rouges', 'Quelques amandes'], alt: 'Remplacer le skyr par du tofu soyeux mixe.' },
      { icon: '🍗', name: 'Dejeuner', time: '12h30', kcal: 620, items: ['Poulet grille', 'Riz complet', 'Brocoli', 'Huile d olive mesuree'] },
      { icon: '🍎', name: 'Collation', time: '16h30', kcal: 180, items: ['Pomme', 'Yaourt nature proteine'] },
      { icon: '🐟', name: 'Diner', time: '20h00', kcal: 580, items: ['Saumon ou tofu', 'Legumes rotis', 'Pommes de terre vapeur'] },
    ],
  },
  {
    id: 'b',
    label: 'Vegetarienne',
    subtitle: 'Proteines vegetales rassasiantes',
    totalKcal: 1750,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200',
    meals: [
      { icon: '🍞', name: 'Petit-dejeuner', time: '8h00', kcal: 390, items: ['Pain complet', 'Oeufs ou tofu brouille', 'Fruit frais'] },
      { icon: '🥗', name: 'Dejeuner', time: '12h30', kcal: 610, items: ['Lentilles', 'Quinoa', 'Crudites', 'Sauce yaourt citron'] },
      { icon: '🥛', name: 'Collation', time: '16h00', kcal: 180, items: ['Skyr ou soja nature', 'Cannelle'] },
      { icon: '🍛', name: 'Diner', time: '19h30', kcal: 570, items: ['Curry pois chiches leger', 'Legumes', 'Riz basmati dose'] },
    ],
  },
  {
    id: 'c',
    label: 'Meal prep',
    subtitle: 'Tout preparer sans y penser',
    totalKcal: 1820,
    image: 'https://images.unsplash.com/photo-1543353071-10c8ba85a904?w=1200',
    meals: [
      { icon: '🥞', name: 'Petit-dejeuner', time: '7h30', kcal: 400, items: ['Pancakes avoine', 'Fromage blanc', 'Banane'] },
      { icon: '🍱', name: 'Dejeuner', time: '12h30', kcal: 650, items: ['Dinde', 'Patate douce', 'Haricots verts', 'Sauce tomate maison'] },
      { icon: '🥕', name: 'Collation', time: '17h00', kcal: 170, items: ['Crudites', 'Houmous leger'] },
      { icon: '🥘', name: 'Diner', time: '20h00', kcal: 600, items: ['Chili leger', 'Legumes', 'Riz dose'] },
    ],
  },
  {
    id: 'd',
    label: 'Jour sport',
    subtitle: 'Plus de glucides autour de l effort',
    totalKcal: 1900,
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200',
    meals: [
      { icon: '🥣', name: 'Petit-dejeuner', time: '7h30', kcal: 450, items: ['Porridge', 'Banane', 'Proteines selon besoin'] },
      { icon: '🍝', name: 'Dejeuner', time: '12h30', kcal: 700, items: ['Pates completes', 'Thon ou tofu', 'Legumes', 'Parmesan dose'] },
      { icon: '🍌', name: 'Avant/apres sport', time: '17h00', kcal: 220, items: ['Banane', 'Yaourt proteine'] },
      { icon: '🥗', name: 'Diner', time: '20h30', kcal: 530, items: ['Omelette', 'Grande salade', 'Pain complet'] },
    ],
  },
  {
    id: 'e',
    label: 'Petit budget',
    subtitle: 'Simple, nourrissant et economique',
    totalKcal: 1760,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200',
    meals: [
      { icon: '🥚', name: 'Petit-dejeuner', time: '8h00', kcal: 380, items: ['Oeufs', 'Pain complet', 'Fruit'] },
      { icon: '🍲', name: 'Dejeuner', time: '12h30', kcal: 620, items: ['Riz', 'Lentilles', 'Carottes', 'Epices'] },
      { icon: '🍏', name: 'Collation', time: '16h30', kcal: 150, items: ['Pomme', 'Fromage blanc'] },
      { icon: '🐟', name: 'Diner', time: '20h00', kcal: 610, items: ['Sardines ou maquereau', 'Pommes de terre', 'Legumes surgeles'] },
    ],
  },
];

export const SECHE_RECIPES = [
  {
    id: 's1',
    title: 'Bowl poulet quinoa',
    description: 'Un dejeuner complet, riche en proteines et facile a preparer.',
    category: 'Sèche',
    meal_category: 'dejeuner',
    prep_time: 15,
    cook_time: 15,
    calories: 520,
    proteins: 42,
    carbs: 48,
    fats: 14,
    servings: 1,
    difficulty: 'facile',
    meal_prep: true,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=900',
    ingredients: ['120g poulet', '70g quinoa cuit', 'Courgette', 'Tomates', 'Citron', '1 c.a.c. huile d olive'],
    steps: ['Cuire le quinoa.', 'Griller le poulet.', 'Couper les legumes.', 'Assembler avec citron et huile.'],
    dietitian_tips: 'Le quinoa complete bien les proteines animales et apporte des fibres.',
  },
  {
    id: 's2',
    title: 'Porridge skyr fruits rouges',
    description: 'Petit-dejeuner rassasiant pour eviter les fringales.',
    category: 'Sèche',
    meal_category: 'petitdej',
    prep_time: 5,
    cook_time: 5,
    calories: 390,
    proteins: 28,
    carbs: 48,
    fats: 8,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=900',
    ingredients: ['45g flocons d avoine', '150g skyr', 'Fruits rouges', 'Cannelle'],
    steps: ['Cuire les flocons avec de l eau ou du lait.', 'Ajouter le skyr hors du feu.', 'Garnir avec les fruits.'],
    dietitian_tips: 'Bon compromis entre glucides utiles et proteines.',
  },
  {
    id: 's3',
    title: 'Omelette legumes et salade',
    description: 'Diner leger, proteine et rapide.',
    category: 'Sèche',
    meal_category: 'diner',
    prep_time: 10,
    cook_time: 8,
    calories: 430,
    proteins: 32,
    carbs: 18,
    fats: 24,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=900',
    ingredients: ['3 oeufs', 'Champignons', 'Epinards', 'Salade verte', 'Vinaigre balsamique'],
    steps: ['Faire revenir les legumes.', 'Ajouter les oeufs battus.', 'Servir avec une salade.'],
    dietitian_tips: 'Pratique les soirs ou les feculents ne sont pas indispensables.',
  },
  {
    id: 's4',
    title: 'Collation fromage blanc cacao',
    description: 'Une collation simple pour calmer la faim.',
    category: 'Sèche',
    meal_category: 'collation',
    prep_time: 3,
    cook_time: 0,
    calories: 180,
    proteins: 20,
    carbs: 14,
    fats: 4,
    servings: 1,
    difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=900',
    ingredients: ['200g fromage blanc', 'Cacao non sucre', 'Quelques framboises'],
    steps: ['Melanger le fromage blanc et le cacao.', 'Ajouter les framboises.'],
    dietitian_tips: 'Utile si le diner est encore loin.',
  },
];

export const SHOPPING_LIST = [
  { cat: 'Proteines', items: ['Blancs de poulet', 'Oeufs', 'Skyr ou fromage blanc', 'Saumon ou poisson blanc', 'Tofu', 'Lentilles'] },
  { cat: 'Feculents', items: ['Flocons d avoine', 'Riz complet', 'Quinoa', 'Patates douces', 'Pain complet'] },
  { cat: 'Legumes', items: ['Brocoli', 'Courgettes', 'Carottes', 'Epinards', 'Salade verte', 'Tomates'] },
  { cat: 'Fruits', items: ['Bananes', 'Pommes', 'Fruits rouges', 'Citrons'] },
  { cat: 'Placard', items: ['Huile d olive', 'Epices', 'Cacao non sucre', 'Moutarde', 'Pois chiches'] },
];

export const SPORT_TIPS = [
  {
    icon: '🚶',
    title: 'Marche quotidienne',
    desc: 'Augmenter la depense sans fatiguer le systeme nerveux.',
    detail: {
      intro: 'La marche est l outil le plus simple pour soutenir une seche durable.',
      points: ['Viser 7 000 a 10 000 pas selon votre niveau', 'Fractionner en petites marches', 'Marcher apres un repas aide souvent la digestion'],
      example: '10 minutes matin, midi et soir suffisent deja a creer une routine.',
      tip: 'Cherchez la regularite avant le nombre parfait.',
    },
  },
  {
    icon: '🏋️',
    title: 'Renforcement',
    desc: 'Conserver la masse musculaire pendant le deficit.',
    detail: {
      intro: 'Le renforcement indique au corps de garder le muscle.',
      points: ['2 a 3 seances par semaine', 'Mouvements simples : squat, tirage, poussees, gainage', 'Progression douce'],
      example: 'Circuit de 25 minutes avec 4 exercices, 3 tours.',
      tip: 'La qualite d execution compte plus que la duree.',
    },
  },
  {
    icon: '💤',
    title: 'Sommeil',
    desc: 'Un mauvais sommeil augmente faim et fatigue.',
    detail: {
      intro: 'Le sommeil influence directement l appetit et la recuperation.',
      points: ['Heure de coucher stable', 'Limiter les ecrans tardifs', 'Eviter de trop baisser les calories si le sommeil chute'],
      example: 'Routine calme de 20 minutes avant le coucher.',
      tip: 'Une bonne nuit vaut parfois mieux qu une seance supplementaire.',
    },
  },
  {
    icon: '🚴',
    title: 'Cardio doux',
    desc: 'Option utile, mais pas obligatoire tous les jours.',
    detail: {
      intro: 'Le cardio doit completer le plan, pas compenser les repas.',
      points: ['Intensite conversationnelle', '1 a 2 seances si l energie suit', 'Eviter les seances punitives'],
      example: '30 minutes de velo tranquille le week-end.',
      tip: 'Si vous etes epuise, baissez le cardio avant de baisser les repas.',
    },
  },
  {
    icon: '🧘',
    title: 'Recuperation',
    desc: 'La progression a besoin de jours plus calmes.',
    detail: {
      intro: 'La recuperation evite que la seche devienne intenable.',
      points: ['Un jour off par semaine', 'Etirements courts', 'Suivre fatigue et douleurs'],
      example: 'Marche douce et mobilite 10 minutes.',
      tip: 'Un jour calme bien place aide souvent a repartir plus fort.',
    },
  },
];

export const DRINKS = [
  { icon: '💧', name: 'Eau', ok: true, rec: '1,5 a 2 L par jour', detail: 'Base de l hydratation. Ajustez selon chaleur, sport et transpiration.' },
  { icon: '☕', name: 'Cafe', ok: true, rec: 'Sans sucre, avec moderation', detail: 'Peut aider la vigilance. Evitez tard dans la journee si le sommeil est fragile.' },
  { icon: '🍵', name: 'The vert', ok: true, rec: '1 a 3 tasses', detail: 'Interressant sans etre magique. L effet principal vient surtout du cadre alimentaire.' },
  { icon: '🥤', name: 'Sodas sucres', ok: false, rec: 'A eviter', detail: 'Ils apportent vite beaucoup de sucre sans satiete durable.' },
  { icon: '🧃', name: 'Jus de fruits', ok: null, rec: 'Occasionnel', detail: 'Un fruit entier rassasie davantage qu un jus.' },
  { icon: '🍷', name: 'Alcool', ok: false, rec: 'Limiter fortement', detail: 'L alcool complique le deficit et peut perturber sommeil et recuperation.' },
  { icon: '🥛', name: 'Boisson proteinee', ok: null, rec: 'Si besoin', detail: 'Utile ponctuellement si les proteines sont difficiles a atteindre avec les repas.' },
];
