// ─── DONNÉES PARTAGÉES PROGRAMME SÈCHE PROGRESSIVE ───────────────────────────

export const WEEKS = [
  {
    num: 1, title: 'Mise en place des habitudes',
    objective: 'Installer les bases sans frustration',
    color: 'from-green-50 to-primary/5',
    habits: ['3 repas structurés par jour', 'Pas de grignotage non planifié', 'Boire 1,5 L eau minimum', 'Manger assis, sans écran'],
    nutrition: 'Commencez à augmenter les protéines (œufs, poulet, légumineuses). Observez vos portions sans forcément les peser. L\'objectif cette semaine est simplement de stabiliser le rythme alimentaire.',
    nutritionDetail: [
      'Visez 3 repas fixes par jour, à des horaires réguliers.',
      'À chaque repas : une source de protéines, des légumes, un féculent en quantité raisonnable.',
      'Pas besoin de peser les aliments cette semaine. Observez vos niveaux de faim avant et après chaque repas.',
      'Si vous avez faim entre les repas, notez-le sans forcément craquer. C\'est une information utile.',
    ],
    activity: 'Marche 20-30 min/jour. Aucune obligation sportive intense cette semaine. L\'objectif est de créer une routine, pas de se dépenser.',
    activityDetail: [
      '20 à 30 minutes de marche à pied par jour.',
      'Vous pouvez diviser : 15 min le matin + 15 min le soir.',
      'Pas d\'intensité élevée cette semaine : votre corps s\'adapte au nouveau rythme alimentaire.',
      'Priorisez les escaliers, les déplacements à pied, les petits gestes du quotidien.',
    ],
    checklist: ['3 repas/jour respectés', 'Hydratation suffisante (1,5 L)', 'Pas de repas sauté', 'Légumes à chaque repas', 'Marche quotidienne'],
    tip: 'Ne cherchez pas la perfection. Une semaine 1 réussie, c\'est simplement avoir essayé chaque jour.',
  },
  {
    num: 2, title: 'Stabilisation des portions',
    objective: 'Apprendre à calibrer sans peser',
    color: 'from-blue-50 to-primary/5',
    habits: ['Assiette : ½ légumes, ¼ protéines, ¼ féculents', 'Manger lentement (20 min minimum)', 'Petit-déjeuner protéiné', 'Limiter les extras (sauces, fromage supplémentaire)'],
    nutrition: 'Réduisez légèrement les portions de féculents en soirée. Conservez les féculents le matin et à midi pour l\'énergie de la journée.',
    nutritionDetail: [
      'Appliquez la méthode de l\'assiette : moitié légumes, un quart protéines, un quart féculents.',
      'Au dîner, vous pouvez réduire les féculents ou les supprimer si vous n\'avez pas d\'activité physique intense dans la soirée.',
      'Mangez lentement : posez votre fourchette entre chaque bouchée. La satiété met 20 minutes à arriver.',
      'Évitez de vous resservir automatiquement. Attendez 10 min avant de décider si vous avez encore faim.',
    ],
    activity: 'Ajoutez 2 séances de renforcement léger (30 min). Continuez la marche quotidienne.',
    activityDetail: [
      '2 séances de renforcement musculaire léger dans la semaine (squats, pompes, abdos, etc.).',
      'Durée : 20 à 30 minutes par séance.',
      'Continuez la marche quotidienne.',
      'Objectif : maintenir le muscle pendant le déficit calorique.',
    ],
    checklist: ['Méthode assiette appliquée', 'Repas assis sans écran', 'Collation saine si faim', 'Séances sport notées', 'Pas de saut de repas'],
    tip: 'La méthode assiette est plus intuitive que de compter les calories. Elle fonctionne à long terme.',
  },
  {
    num: 3, title: 'Optimisation des protéines',
    objective: 'Atteindre 1,6 g de protéines par kg de poids corporel',
    color: 'from-orange-50 to-secondary/5',
    habits: ['Source de protéine à chaque repas', 'Collation protéinée si faim (yaourt, fromage blanc)', 'Cuisiner en batch le dimanche', 'Varier les sources (animal + végétal)'],
    nutrition: 'Protéines animales et végétales alternées. Légumineuses 3x/semaine. Évitez les plats sans protéines.',
    nutritionDetail: [
      'Sources animales : poulet, dinde, saumon, cabillaud, thon, oeufs, yaourt grec, skyr.',
      'Sources végétales : lentilles, pois chiches, tofu, edamames, haricots rouges.',
      'Un repas sans protéines est un repas qui ne soutient pas la satiété ni le muscle.',
      'Exemple de petit-déjeuner protéiné : 2 oeufs + fromage blanc + fruit. Ou : porridge + skyr + noix.',
    ],
    activity: '3 séances de renforcement cette semaine. Intensité modérée. Augmentez légèrement la charge.',
    activityDetail: [
      '3 séances de renforcement musculaire cette semaine.',
      'Exemple de programme simple : lundi squats/fentes, mercredi haut du corps, vendredi full body.',
      'Augmentez légèrement la difficulté par rapport à la semaine 2.',
      'Récupération : dormez 7 à 9h. Le muscle se construit pendant le sommeil.',
    ],
    checklist: ['Protéines à chaque repas', 'Batch cooking fait', 'Légumineuses 3x', 'Collation protéinée si faim', '3 séances sport'],
    tip: 'Préparer ses repas le dimanche réduit de 80% les décisions alimentaires stressantes de la semaine.',
  },
  {
    num: 4, title: 'Gestion des envies sucrées',
    objective: 'Réduire la dépendance au sucre sans privation',
    color: 'from-pink-50 to-secondary/5',
    habits: ['Fruit entier si envie sucrée', 'Carreau de chocolat noir 70% après repas', 'Éviter les boissons sucrées', 'Identifier les déclencheurs d\'envie'],
    nutrition: 'Les envies sucrées sont souvent liées à un repas insuffisant. Vérifiez que vos repas sont assez rassasiants (fibres + protéines).',
    nutritionDetail: [
      'Une envie de sucre après le repas est souvent un signal de manque de fibres ou de protéines dans le repas.',
      'Fruit entier plutôt que jus : les fibres ralentissent l\'absorption du sucre.',
      '1 à 2 carreaux de chocolat noir (70%+) = satisfait l\'envie sucrée avec des antioxydants.',
      'Les édulcorants entretiennent la dépendance au sucre. Préférez réduire progressivement la quantité.',
    ],
    activity: 'Continuez 3 séances/semaine. Ajoutez 10 min de marche après le dîner pour stabiliser la glycémie.',
    activityDetail: [
      'La marche post-repas (10-15 min) aide à réduire le pic glycémique.',
      'Elle diminue les envies sucrées en soirée.',
      'Continuez vos 3 séances de renforcement.',
      'Si vous avez très envie de sucre en soirée : buvez une infusion et attendez 15 min.',
    ],
    checklist: ['Zéro boisson sucrée', 'Fruit si envie sucrée', 'Repas rassasiants', 'Pas de grignotage nocturne', 'Marche post-dîner'],
    tip: 'Interdire un aliment augmente son attrait. Autoriser le chocolat noir permet de ne pas craquer sur le reste.',
  },
  {
    num: 5, title: 'Amélioration de la qualité des glucides',
    objective: 'Passer aux féculents complets et à index glycémique bas',
    color: 'from-yellow-50 to-primary/5',
    habits: ['Riz complet, pâtes complètes, pain complet', 'Patate douce plutôt que pomme de terre', 'Légumineuses comme source de glucides', 'Lire les étiquettes (sucre ajouté)'],
    nutrition: 'Les glucides complexes stabilisent la glycémie et prolongent la satiété. Ne les éliminez pas !',
    nutritionDetail: [
      'Index glycémique (IG) bas = énergie stable, pas de coup de barre, moins de fringales.',
      'Riz complet (IG 50) vs riz blanc (IG 72). Patate douce (IG 44) vs pomme de terre (IG 78).',
      'Les légumineuses ont un IG très bas et apportent protéines + fibres en bonus.',
      'Pain complet : vérifiez que "complet" est bien la première farine listée dans les ingrédients.',
    ],
    activity: '3 séances renforcement + 1 cardio léger (vélo, natation). Durée 30-40 min.',
    activityDetail: [
      'Ajoutez 1 séance de cardio léger à votre programme.',
      'Vélo, natation, elliptique ou footing léger : 30 à 40 minutes.',
      'Intensité : vous devez pouvoir tenir une conversation.',
      'Ne compensez pas en mangeant plus après le cardio.',
    ],
    checklist: ['Féculents complets choisis', 'Pas de pain blanc', 'Légumineuses 3x', 'Cardio ajouté', 'Étiquettes lues'],
    tip: 'Remplacer le riz blanc par du riz complet est l\'une des modifications les plus simples et les plus impactantes.',
  },
  {
    num: 6, title: 'Organisation meal prep',
    objective: 'Préparer les repas à l\'avance pour ne jamais improviser',
    color: 'from-teal-50 to-primary/5',
    habits: ['Cuisiner 3-4 portions le dimanche', 'Lunch boxes prêtes pour la semaine', 'Liste de courses établie le samedi', 'Préparer des collations saines'],
    nutrition: 'Le meal prep évite les écarts alimentaires liés au manque de temps. Cuisinez simple et varié.',
    nutritionDetail: [
      'Exemple de session meal prep : 1h30 le dimanche pour 4 repas de semaine.',
      'Préparez les bases : riz complet, quinoa, lentilles cuites, légumes rôtis.',
      'Faites varier les protéines selon les jours (poulet, saumon, oeufs, légumineuses).',
      'Conservez au frigo 3-4 jours maximum, ou congelez si besoin.',
    ],
    activity: '3-4 séances/semaine. Intégrez le sport dans votre agenda comme un rendez-vous fixe.',
    activityDetail: [
      'À ce stade du programme, le sport devrait être ancré dans votre routine.',
      '3 à 4 séances : 2-3 renforcement + 1 cardio.',
      'Planifiez vos séances en début de semaine dans votre agenda.',
      'Récupération active : marche, yoga ou étirements les jours de repos.',
    ],
    checklist: ['Meal prep fait dimanche', 'Lunch boxes prêtes', 'Liste courses faite', 'Variété dans les repas', 'Sport planifié'],
    tip: 'Le meal prep est le meilleur outil anti-écart. Quand le repas est prêt, on ne cherche pas autre chose.',
  },
  {
    num: 7, title: 'Ajustements fins',
    objective: 'Affiner la progression selon les résultats',
    color: 'from-purple-50 to-primary/5',
    habits: ['Peser-vous 1x/semaine (même condition)', 'Notez votre énergie et humeur', 'Adaptez les portions si la faim est trop forte', 'Vérifiez vos extras cachés'],
    nutrition: 'Si la perte ralentit, vérifiez les extras (sauces, huile). Si énergie basse, augmentez légèrement les glucides.',
    nutritionDetail: [
      'Les "petits extras" s\'accumulent sans qu\'on s\'en rende compte : huile, beurre, sauces, fromage.',
      'Si vous stagnez depuis 2 semaines : réduisez de 100-150 kcal ou augmentez l\'activité.',
      'Si vous êtes épuisé(e) : ajoutez 20-30g de féculents supplémentaires le matin.',
      'Adaptez, ne subissez pas. Ce programme est un guide, pas une règle absolue.',
    ],
    activity: 'Maintenez le rythme établi. Vous pouvez intensifier légèrement si vous vous sentez à l\'aise.',
    activityDetail: [
      'Augmentez légèrement la charge ou la durée si vous vous sentez bien.',
      'Si vous êtes fatigué(e), réduisez l\'intensité mais ne supprimez pas les séances.',
      'Écoutez votre corps : douleurs inhabituelles = repos.',
      'Continuez la marche quotidienne.',
    ],
    checklist: ['Pesée hebdomadaire', 'Journal alimentaire tenu', 'Énergie stable', 'Pas de restriction excessive', 'Ajustements notés'],
    tip: 'Une plateau de poids n\'est pas un échec. C\'est un signal d\'ajustement. Analysez avant de réagir.',
  },
  {
    num: 8, title: 'Bilan et maintien',
    objective: 'Consolider les acquis et préparer la suite',
    color: 'from-green-50 to-secondary/5',
    habits: ['Évaluez les habitudes installées', 'Identifiez ce qui a bien fonctionné', 'Planifiez la suite (maintien ou nouvelle phase)', 'Consultez un professionnel si besoin'],
    nutrition: 'Augmentez légèrement les calories pour passer en phase de maintien (+200-300 kcal). Ne reprenez pas les anciens comportements.',
    nutritionDetail: [
      'Le maintien est souvent la phase la plus difficile. Planifiez-le sérieusement.',
      'Augmentez progressivement les calories (+100 kcal/semaine) jusqu\'au poids stable.',
      'Conservez les habitudes acquises : repas structurés, protéines, légumes, hydratation.',
      'Félicitez-vous pour les 8 semaines complétées. C\'est une vraie réussite.',
    ],
    activity: 'Continuez votre routine sportive. Le sport est maintenant une habitude à conserver pour la vie.',
    activityDetail: [
      'Le sport ne doit plus être perçu comme un outil de perte de poids, mais comme un pilier de santé.',
      'Maintenez 2-3 séances par semaine minimum.',
      'Explorez de nouvelles activités pour garder la motivation.',
      'Si vous recommencez un programme, attendez 2-4 semaines de maintien avant.',
    ],
    checklist: ['Bilan écrit', 'Habitudes identifiées', 'Plan de maintien défini', 'Rendez-vous diété si besoin', 'Sport maintenu'],
    tip: 'Ce n\'est pas la fin d\'un régime. C\'est le début d\'un nouveau mode de vie.',
  },
];

export const DAY_PLANS = [
  {
    id: 'a', label: 'Journée A — Standard',
    subtitle: 'La journée type de base du programme',
    totalKcal: 1780,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 370, items: ["Porridge 50g flocons d'avoine + 200ml lait végétal", '1 banane', '1 yaourt grec nature (150g)', 'Café ou thé sans sucre'], alt: '2 oeufs brouillés + 2 tranches pain complet + 1 kiwi' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 540, items: ['150g poulet grillé', '80g riz complet (poids cru)', 'Salade verte + tomates cerises', '1 filet huile olive', '1 yaourt nature'], alt: 'Bowl quinoa pois chiches avocat' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 160, items: ['1 pomme', '15g amandes (environ 12 amandes)'], alt: 'Fromage blanc 0% + 1 c.à.c. miel' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 460, items: ['130g saumon grillé', 'Haricots verts vapeur', '1 petite patate douce (100g)', '1 filet citron'], alt: 'Omelette 3 oeufs + épinards + pain complet' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['1,5 à 2 L eau plate', 'Thé vert ou infusions', 'Café max 3/jour, sans sucre'], alt: 'Eau pétillante si envie de bulles' },
    ],
  },
  {
    id: 'b', label: 'Journée B — Végétarienne',
    subtitle: 'Une journée 100% végétarienne et rassasiante',
    totalKcal: 1750,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 360, items: ['2 tranches pain complet grillé', '2 oeufs pochés', '1/2 avocat', 'Tomates cerises', 'Café ou thé'], alt: 'Skyr 200g + fruits rouges + graines chia + noix' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 520, items: ['Salade lentilles 200g', '60g feta', '1/2 concombre + tomates cerises', 'Herbes fraîches + vinaigrette légère'], alt: 'Buddha bowl tofu riz complet légumes' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 175, items: ['200g skyr nature', '80g fruits rouges', '1 c.à.s. graines chia'], alt: '1 fruit + 1 poignée noix' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 440, items: ['Omelette 3 oeufs aux champignons', '80g épinards sautés à l\'ail', '1 tranche pain complet', '1 fromage blanc 0%'], alt: 'Soupe légumes pois chiches + pain complet' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['1,5 à 2 L eau', 'Thé vert 2-3 tasses', 'Infusions le soir'], alt: '' },
    ],
  },
  {
    id: 'c', label: 'Journée C — Meal Prep',
    subtitle: 'Tout préparable à l\'avance pour la semaine',
    totalKcal: 1800,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 380, items: ['Overnight oats préparés la veille', "50g flocons d'avoine + 200ml lait végétal", '1 c.à.s. beurre amande + fruits rouges', '1 c.à.c. graines chia'], alt: 'Galettes avoine-courgette (préparées dimanche) + fromage blanc' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 530, items: ['Lunch box : dinde riz complet courgettes', '150g dinde + 80g riz complet', '150g courgettes poêlées à l\'ail', '1 yaourt'], alt: 'Chili dinde haricots rouges (portion congelée)' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 160, items: ['Fromage blanc 0% + pomme + cannelle', '200g fromage blanc + 1 pomme + 1 c.à.c. noix'], alt: 'Energy balls dattes-cacao maison (2-3 boules)' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 480, items: ['Soupe légumes pois chiches (portion meal prep)', '2 tranches pain complet', '1 yaourt nature'], alt: 'Wrap thon crudités sauce yaourt (rapide)' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['1,5 à 2 L eau', 'Thé vert ou café sans sucre', 'Bouteille d\'eau à emporter'], alt: '' },
    ],
  },
  {
    id: 'd', label: 'Journée D — Jour de sport',
    subtitle: 'Plus de glucides pour alimenter l\'effort',
    totalKcal: 1900,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 420, items: ["Porridge 60g d'avoine + lait végétal", '1 banane + 1 c.à.s. beurre amande', '1 yaourt grec + 1 c.à.c. miel', 'Café sans sucre'], alt: 'Toast complet x2 + 2 oeufs brouillés + avocat' },
      { time: '12h30', name: 'Déjeuner (avant sport)', icon: '☀️', kcal: 580, items: ['Bowl poulet quinoa (grosse portion)', '150g poulet + 100g quinoa cuit', 'Légumes rôtis', '1 filet huile olive'], alt: 'Pâtes complètes + thon + tomates' },
      { time: '16h00', name: 'Post-sport', icon: '🏋️', kcal: 220, items: ['Skyr 200g + 1 banane', 'Ou : shake protéiné + fruit'], alt: '2 oeufs durs + 1 fruit' },
      { time: '19h30', name: 'Dîner (léger)', icon: '🌙', kcal: 430, items: ['130g cabillaud vapeur', 'Haricots verts + carottes', '80g riz complet (réduit le soir)', '1 fromage blanc'], alt: 'Soupe légumes + pain complet + yaourt' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['2 à 2,5 L eau (jour de sport)', 'Pendant le sport : eau ou boisson sans sucre', 'Café avant sport si habitude'], alt: '' },
    ],
  },
  {
    id: 'e', label: 'Journée E — Budget serré',
    subtitle: 'Équilibre parfait pour moins de 5€/jour',
    totalKcal: 1760,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
    meals: [
      { time: '7h30', name: 'Petit-déjeuner', icon: '🌅', kcal: 350, items: ["50g flocons d'avoine + 200ml lait (tout type)", '1 banane mûre', '1 yaourt nature 0%', 'Café ou thé'], alt: '2 oeufs + pain complet + 1 fruit de saison' },
      { time: '12h30', name: 'Déjeuner', icon: '☀️', kcal: 510, items: ['Curry lentilles corail', '200g lentilles cuites + tomates + épices', '80g riz complet', '1 yaourt'], alt: 'Soupe pois chiches légumes + pain complet' },
      { time: '16h00', name: 'Collation', icon: '🍎', kcal: 150, items: ['1 pomme ou banane', '1 poignée noix (15g)'], alt: 'Fromage blanc + cannelle' },
      { time: '19h30', name: 'Dîner', icon: '🌙', kcal: 490, items: ['Omelette 3 oeufs courgette', 'Courgette + ail + herbes', 'Salade verte + vinaigrette légère', '1 tranche pain complet'], alt: 'Galettes avoine-légumes + fromage blanc' },
      { time: 'Journée', name: 'Boissons', icon: '💧', kcal: 0, items: ['Eau du robinet filtrée : 1,5-2 L', 'Thé en vrac (économique)', 'Café classique'], alt: '' },
    ],
  },
];

export const SECHE_RECIPES = [
  {
    id: 's1', title: 'Bowl Poulet Quinoa Crudités',
    description: 'Un bowl complet et équilibré, idéal pour la sèche : protéines élevées, glucides modérés, plein de fibres.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 15, cook_time: 15, calories: 480, proteins: 40, carbs: 42, fats: 12, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    ingredients: ['150g de blanc de poulet', '80g de quinoa cru', '1 concombre', '10 tomates cerises', '1 poivron', '1 c.à.s. huile olive', 'Jus de citron', 'Persil', 'Sel, poivre'],
    steps: ['Cuire le quinoa (15 min).', 'Griller le poulet assaisonné 10 min.', 'Couper les légumes en petits morceaux.', 'Assembler le bowl et arroser de citron et huile.'],
    dietitian_tips: 'Le quinoa est une protéine végétale complète. Ce bowl couvre environ 40g de protéines pour seulement 480 kcal.',
    meal_prep: true,
  },
  {
    id: 's2', title: 'Omelette Épinards Champignons',
    description: 'Un repas léger, rapide et ultra-protéiné. Parfait le soir pour le dîner.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 5, cook_time: 8, calories: 280, proteins: 24, carbs: 6, fats: 16, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600',
    ingredients: ['3 oeufs entiers', '100g de champignons', '80g épinards frais', '1 c.à.c. huile olive', 'Ail', 'Sel, poivre', 'Herbes de Provence'],
    steps: ["Faire revenir les champignons et épinards à l'ail.", 'Battre les oeufs et assaisonner.', 'Verser les oeufs sur les légumes.', 'Plier et cuire 2 min supplémentaires.'],
    dietitian_tips: 'Moins de 300 kcal pour 24g de protéines. Excellent ratio pour la sèche. Ajoutez du fromage blanc en accompagnement.',
  },
  {
    id: 's3', title: 'Skyr Fruits Rouges Chia',
    description: 'La collation idéale pour la sèche : ultra-protéinée, peu calorique, rassasiante.',
    category: 'collation', meal_category: 'collation',
    prep_time: 3, cook_time: 0, calories: 175, proteins: 18, carbs: 16, fats: 3, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600',
    ingredients: ['200g de skyr nature', '80g de fruits rouges (frais ou surgelés)', '1 c.à.s. graines de chia', '1 c.à.c. miel optionnel'],
    steps: ['Verser le skyr dans un bol.', 'Ajouter les fruits rouges.', 'Parsemer de graines de chia.', 'Ajouter le miel si besoin.'],
    dietitian_tips: 'Le skyr islandais contient 11g de protéines/100g avec très peu de lipides. Les graines de chia apportent des oméga-3 et des fibres.',
  },
  {
    id: 's4', title: 'Wrap Thon Crudités Sauce Yaourt',
    description: 'Un déjeuner express riche en protéines, pratique à emporter.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 0, calories: 380, proteins: 32, carbs: 34, fats: 10, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600',
    ingredients: ['1 tortilla complète', '1 boîte thon au naturel (160g)', '1/2 concombre', '2 tomates', '50g de roquette', '2 c.à.s. yaourt 0%', 'Moutarde', 'Citron', 'Sel, poivre'],
    steps: ['Préparer la sauce : yaourt + moutarde + citron.', 'Égoutter le thon.', 'Tartiner la tortilla.', 'Disposer thon, légumes, roquette.', 'Rouler et couper.'],
    dietitian_tips: 'Le thon au naturel est la protéine la plus économique et pratique. 25g de protéines pour 100g.',
    meal_prep: true,
  },
  {
    id: 's5', title: 'Saumon Légumes Rôtis Patate Douce',
    description: 'Un dîner complet avec des oméga-3, des antioxydants et des glucides de qualité.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 25, calories: 490, proteins: 36, carbs: 38, fats: 18, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600',
    ingredients: ['150g de pavé de saumon', '1 patate douce moyenne', '1 courgette', '1 poivron', 'Huile olive', 'Thym', 'Sel, poivre', 'Citron'],
    steps: ['Préchauffer le four à 200°C.', 'Couper les légumes et la patate douce.', 'Enfourner les légumes 15 min.', 'Ajouter le saumon assaisonné, cuire encore 10-12 min.', 'Servir avec un filet de citron.'],
    dietitian_tips: "La patate douce a un index glycémique bien plus bas que la pomme de terre classique. Le saumon est LA source d'oméga-3 EPA/DHA.",
  },
  {
    id: 's6', title: 'Dinde Riz Complet Courgettes',
    description: 'Le classique sportif : viande maigre, glucides complexes et légumes verts.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 20, calories: 450, proteins: 42, carbs: 44, fats: 8, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600',
    ingredients: ['150g de filet de dinde', '80g de riz complet cru', '2 courgettes', '1 c.à.s. huile olive', 'Ail', 'Herbes de Provence', 'Sel, poivre'],
    steps: ['Cuire le riz complet (18-20 min).', 'Couper les courgettes en rondelles.', 'Griller la dinde assaisonnée.', "Poêler les courgettes à l'ail.", 'Assembler et servir.'],
    dietitian_tips: 'La dinde est encore plus maigre que le poulet. Excellente alternative pour varier les protéines.',
    meal_prep: true,
  },
  {
    id: 's7', title: 'Salade Lentilles Feta Concombre',
    description: 'Une salade végétarienne riche en protéines et en fibres, idéale en déjeuner.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 0, calories: 360, proteins: 20, carbs: 40, fats: 12, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600',
    ingredients: ['200g de lentilles cuites', '60g de feta allégée', '1/2 concombre', '10 tomates cerises', '1/4 oignon rouge', 'Menthe fraîche', 'Huile olive', 'Vinaigre balsamique'],
    steps: ['Égoutter les lentilles.', 'Couper les légumes.', 'Émietter la feta.', 'Mélanger tous les ingrédients.', 'Assaisonner et ajouter la menthe.'],
    dietitian_tips: "Les lentilles sont l'une des meilleures sources de protéines végétales. Riches en fer et en fibres qui prolongent la satiété.",
  },
  {
    id: 's8', title: 'Porridge Protéiné Banane Cannelle',
    description: 'Un petit-déjeuner rassasiant et nutritif pour bien démarrer la journée en mode sèche.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 5, cook_time: 5, calories: 370, proteins: 20, carbs: 48, fats: 8, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1571748982800-fa51082c2224?w=600',
    ingredients: ["50g de flocons d'avoine", '200ml de lait végétal', '30g de protéine vanille (ou skyr)', '1 banane', '1 c.à.c. cannelle', '1 c.à.s. beurre amande'],
    steps: ['Chauffer le lait à feu doux.', "Ajouter les flocons d'avoine.", 'Cuire 4-5 min en remuant.', 'Hors feu, incorporer la protéine ou le skyr.', 'Garnir de banane, cannelle et beurre amande.'],
    dietitian_tips: "Les flocons d'avoine ont l'un des meilleurs indices de satiété parmi les céréales. La cannelle aide à réguler la glycémie.",
  },
  {
    id: 's9', title: 'Cabillaud Haricots Verts Pommes de Terre',
    description: 'Un plat complet, léger et facile à préparer pour un dîner sain.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 20, calories: 380, proteins: 34, carbs: 32, fats: 6, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600',
    ingredients: ['150g de filet de cabillaud', '200g de haricots verts', '150g de pommes de terre', 'Citron', 'Herbes de Provence', 'Huile olive', 'Sel, poivre'],
    steps: ["Cuire les pommes de terre à l'eau (15 min).", 'Cuire les haricots verts vapeur (10 min).', 'Poêler le cabillaud assaisonné (3-4 min/côté).', 'Servir avec un filet de citron.'],
    dietitian_tips: 'Le cabillaud est le poisson le plus maigre (environ 80 kcal/100g). Excellent en période de sèche.',
  },
  {
    id: 's10', title: 'Buddha Bowl Tofu Légumes Croquants',
    description: 'Un bowl végétarien complet et coloré, riche en protéines végétales.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 15, cook_time: 20, calories: 430, proteins: 22, carbs: 50, fats: 14, servings: 1, difficulty: 'moyen',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600',
    ingredients: ['150g de tofu ferme', '80g de riz complet', '1 carotte', '1/2 avocat', '80g de roquette', 'Edamames', 'Sauce soja', 'Gingembre', 'Huile sésame'],
    steps: ['Couper et mariner le tofu (sauce soja, gingembre).', 'Cuire le riz complet.', 'Poêler le tofu 3 min/côté.', 'Préparer les légumes crus.', 'Assembler le bowl et arroser de sauce sésame.'],
    dietitian_tips: 'Le tofu ferme contient 15g de protéines/100g. Très polyvalent et se marie bien avec les saveurs asiatiques.',
  },
  {
    id: 's11', title: 'Poulet Curry Léger Lait de Coco Light',
    description: "Un curry savoureux et légèrement allégé pour rester dans l'objectif calorique.",
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 20, calories: 460, proteins: 38, carbs: 30, fats: 14, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    ingredients: ['300g de blanc de poulet', '200ml de lait de coco light', '1 c.à.s. pâte de curry jaune', '1 oignon', '2 gousses ail', '1 poivron', 'Coriandre', 'Riz basmati'],
    steps: ['Faire revenir oignon et ail.', 'Ajouter la pâte de curry 1 min.', 'Ajouter le poulet découpé.', 'Verser le lait de coco et mijoter 15 min.', 'Servir sur riz basmati avec coriandre.'],
    dietitian_tips: 'Le lait de coco light contient 2x moins de calories que le classique. Ce plat reste très protéiné et satisfaisant.',
    meal_prep: true,
  },
  {
    id: 's12', title: 'Soupe Complète Légumes Pois Chiches',
    description: 'Une soupe repas consistante et réconfortante pour les soirées fraîches.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 25, calories: 320, proteins: 14, carbs: 42, fats: 6, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600',
    ingredients: ['400g de pois chiches cuits', '2 carottes', '1 courgette', '1 boîte tomates pelées', '1 oignon', 'Curcuma', 'Cumin', 'Bouillon de légumes', 'Persil'],
    steps: ['Faire revenir oignon avec les épices.', 'Ajouter carottes et courgette coupées.', 'Verser tomates et bouillon.', 'Cuire 15 min, ajouter pois chiches.', 'Mijoter encore 5-10 min. Servir avec persil.'],
    dietitian_tips: 'Les pois chiches sont une source de protéines végétales et de fibres. Cette soupe est très rassasiante pour un budget calorique faible.',
    meal_prep: true,
  },
  {
    id: 's13', title: 'Fromage Blanc Pomme Cannelle',
    description: 'La collation parfaite pour la sèche : douce, fraîche et protéinée.',
    category: 'collation', meal_category: 'collation',
    prep_time: 5, cook_time: 0, calories: 180, proteins: 14, carbs: 20, fats: 2, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600',
    ingredients: ['200g de fromage blanc 0%', '1 pomme', '1 c.à.c. cannelle', '1 c.à.c. miel (optionnel)', '1 c.à.s. noix concassées'],
    steps: ['Verser le fromage blanc dans un bol.', 'Couper la pomme en dés.', 'Ajouter cannelle et miel.', 'Parsemer de noix concassées.'],
    dietitian_tips: 'Le fromage blanc 0% est une excellente source de caséine (protéine à digestion lente). Parfait en collation ou au dîner.',
  },
  {
    id: 's14', title: 'Steak Haché 5% Légumes Grillés',
    description: 'Un repas simple, économique et très protéiné, parfait en semaine.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 5, cook_time: 15, calories: 390, proteins: 36, carbs: 20, fats: 16, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600',
    ingredients: ['150g steak haché 5%', '1 courgette', '1 aubergine', '1 poivron', 'Huile olive', 'Herbes de Provence', 'Sel, poivre', 'Moutarde'],
    steps: ['Couper les légumes en tranches.', 'Les griller au four 15 min à 200°C.', 'Cuire le steak haché 3-4 min/côté.', 'Servir avec légumes et moutarde.'],
    dietitian_tips: 'Le steak haché 5% de MG est idéal en sèche. Il apporte du zinc et du fer héminique bien assimilé.',
  },
  {
    id: 's15', title: "Galettes Flocons d'Avoine Oeuf Courgette",
    description: 'Des galettes maison légères et protéinées, à manger chaud ou froid.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 10, cook_time: 10, calories: 310, proteins: 20, carbs: 28, fats: 10, servings: 2, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600',
    ingredients: ["80g de flocons d'avoine", '2 oeufs', '1 courgette râpée', '30g de parmesan râpé', 'Ail', 'Herbes fraîches', 'Sel, poivre'],
    steps: ["Râper la courgette et presser pour enlever l'eau.", "Mélanger avec les flocons d'avoine, les oeufs et le parmesan.", 'Former des galettes.', 'Cuire à la poêle 3-4 min/côté.'],
    dietitian_tips: "Alternative saine aux galettes industrielles. Riches en fibres grâce à l'avoine, et protéinées grâce aux oeufs.",
    meal_prep: true,
  },
  {
    id: 's16', title: 'Salade Oeufs Durs Avocat Tomate',
    description: 'Une salade composée riche en bonnes graisses et en protéines.',
    category: 'déjeuner', meal_category: 'dejeuner',
    prep_time: 10, cook_time: 10, calories: 340, proteins: 16, carbs: 12, fats: 24, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    ingredients: ['2 oeufs durs', '1/2 avocat', '2 tomates', 'Roquette', '1 c.à.s. huile olive', 'Jus de citron', 'Sel, poivre', 'Ciboulette'],
    steps: ["Cuire les oeufs durs (10 min dans l'eau bouillante).", 'Couper avocat, tomates et oeufs.', 'Mélanger avec la roquette.', 'Assaisonner huile et citron.'],
    dietitian_tips: "L'avocat apporte des acides gras monoinsaturés bénéfiques pour le coeur. Cette salade est faible en glucides.",
  },
  {
    id: 's17', title: 'Crevettes Nouilles de Riz Légumes',
    description: 'Un plat asiatique léger et parfumé, prêt en moins de 20 minutes.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 10, calories: 400, proteins: 30, carbs: 48, fats: 6, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=600',
    ingredients: ['150g de crevettes décortiquées', '80g de nouilles de riz', '1 poivron', '100g de germes de soja', 'Sauce soja', 'Huile de sésame', 'Gingembre', 'Coriandre', 'Citron vert'],
    steps: ['Faire tremper ou cuire les nouilles selon le paquet.', 'Faire sauter les crevettes et légumes 3-4 min.', 'Ajouter sauce soja et gingembre.', 'Mélanger avec les nouilles.', 'Servir avec coriandre et citron vert.'],
    dietitian_tips: 'Les crevettes sont très maigres (moins de 100 kcal/100g) pour 20g de protéines. Les nouilles de riz sont sans gluten.',
  },
  {
    id: 's18', title: 'Chili Léger Haricots Rouges Dinde',
    description: 'Un chili revisité plus léger, riche en fibres et en protéines.',
    category: 'dîner', meal_category: 'diner',
    prep_time: 10, cook_time: 30, calories: 420, proteins: 36, carbs: 40, fats: 10, servings: 3, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600',
    ingredients: ['300g de dinde hachée', '400g de haricots rouges cuits', '1 boîte de tomates', '1 oignon', '2 gousses ail', '1 c.à.s. cumin', '1 c.à.c. piment doux', 'Coriandre fraîche'],
    steps: ['Faire revenir oignon et ail.', 'Ajouter la dinde hachée et brunir.', 'Incorporer les épices puis les tomates.', 'Ajouter les haricots rouges.', 'Mijoter 20 min. Servir avec coriandre.'],
    dietitian_tips: 'Ce chili se conserve 4 jours au frigo et se congèle très bien. Parfait pour le meal prep hebdomadaire.',
    meal_prep: true,
  },
  {
    id: 's19', title: 'Pancakes Protéinés Banane',
    description: 'Des pancakes légers et nutritifs pour un petit-déjeuner qui change du porridge.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 5, cook_time: 10, calories: 340, proteins: 22, carbs: 38, fats: 8, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600',
    ingredients: ['1 banane mûre', '2 oeufs', "30g de flocons d'avoine mixés", '1/2 c.à.c. levure', 'Cannelle', '1 c.à.c. huile coco'],
    steps: ['Écraser la banane.', 'Mélanger avec oeufs, flocons, cannelle, levure.', 'Cuire en petits disques à la poêle (2 min/côté).', 'Servir avec yaourt grec et fruits.'],
    dietitian_tips: 'Aucun sucre ajouté : la banane suffit à sucrer naturellement. Très protéinés grâce aux oeufs.',
  },
  {
    id: 's20', title: 'Yaourt Grec Muesli Fruits',
    description: 'Un petit-déjeuner express, crémeux et rassasiant.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 3, cook_time: 0, calories: 310, proteins: 18, carbs: 36, fats: 10, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=600',
    ingredients: ['200g yaourt grec nature', '30g de muesli sans sucre ajouté', '1 kiwi ou 80g fruits rouges', '10g de noix', '1 c.à.c. miel (optionnel)'],
    steps: ['Verser le yaourt dans un bol.', 'Ajouter le muesli et les fruits.', 'Parsemer de noix.', 'Déguster immédiatement (ou préparer la veille).'],
    dietitian_tips: "Le yaourt grec apporte deux fois plus de protéines qu'un yaourt classique. Idéal pour tenir jusqu'au déjeuner.",
  },
  {
    id: 's21', title: 'Toast Complet Avocat Oeuf',
    description: 'Le toast healthy par excellence : avocat, oeuf et pain complet.',
    category: 'petit-déjeuner', meal_category: 'petitdej',
    prep_time: 5, cook_time: 5, calories: 355, proteins: 17, carbs: 30, fats: 20, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600',
    ingredients: ['2 tranches pain complet', '1/2 avocat', '2 oeufs', 'Jus de citron', 'Sel, poivre', 'Piment doux', 'Ciboulette'],
    steps: ['Griller les tranches de pain.', "Écraser l'avocat avec citron, sel.", 'Cuire les oeufs au plat ou pochés.', 'Tartiner le pain, déposer les oeufs.'],
    dietitian_tips: "L'avocat fournit des graisses monoinsaturées qui améliorent l'absorption des vitamines liposolubles. Très rassasiant.",
  },
  {
    id: 's22', title: 'Mousse de Fromage Blanc Cacao',
    description: 'Un dessert ou collation chocolaté, léger et protéiné.',
    category: 'collation', meal_category: 'collation',
    prep_time: 5, cook_time: 0, calories: 160, proteins: 15, carbs: 12, fats: 4, servings: 1, difficulty: 'facile',
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600',
    ingredients: ['200g fromage blanc 0%', '1 c.à.s. cacao pur non sucré', '1 c.à.c. miel ou érythritol', '1 pincée cannelle', 'Quelques éclats de chocolat noir 70%'],
    steps: ['Mélanger fromage blanc et cacao vigoureusement.', 'Ajouter le miel et la cannelle.', 'Réfrigérer 15 min pour une texture plus ferme.', 'Garnir de chocolat noir concassé.'],
    dietitian_tips: 'Le cacao pur est riche en magnésium et antioxydants. Cette mousse satisfait les envies de chocolat sans excès calorique.',
  },
];

export const SHOPPING_LIST = [
  { cat: 'Protéines 🥩', items: ['Blanc de poulet (500g)', 'Filet de dinde (300g)', 'Saumon (2 pavés)', 'Cabillaud (300g)', 'Thon au naturel (3 boîtes)', 'Oeufs (12)', 'Tofu ferme (200g)', 'Dinde hachée (300g)', 'Steak haché 5% (2)', 'Crevettes décortiquées (200g)'] },
  { cat: 'Féculents 🌾', items: ['Riz complet (500g)', 'Quinoa (300g)', "Flocons d'avoine (500g)", 'Nouilles de riz (200g)', 'Pain complet (1 paquet)', 'Lentilles cuites (2 boîtes)', 'Pois chiches cuits (2 boîtes)', 'Haricots rouges (1 boîte)', 'Pâtes complètes (500g)', 'Patate douce (2)'] },
  { cat: 'Légumes 🥦', items: ['Épinards frais (200g)', 'Courgettes (4)', 'Poivrons (3 variés)', 'Champignons (200g)', 'Haricots verts (300g)', 'Roquette (150g)', 'Tomates cerises (250g)', 'Concombres (2)', 'Carottes (4)', 'Aubergine (1)', 'Ail (1 tête)', 'Oignons (3)', 'Salade verte (1)'] },
  { cat: 'Fruits 🍎', items: ['Bananes (6)', 'Pommes (4)', 'Fruits rouges surgelés (300g)', 'Citrons (4)', 'Kiwis (4)', 'Pomme (4 pour collations)'] },
  { cat: 'Produits frais 🥛', items: ['Skyr nature (2 x 450g)', 'Fromage blanc 0% (2 x 500g)', 'Yaourt grec nature (6)', 'Feta allégée (100g)', 'Lait végétal non sucré (1L)', 'Oeufs (12 si pas déjà achetés)'] },
  { cat: 'Épicerie 🫙', items: ["Huile d'olive extra vierge (1 bouteille)", 'Sauce soja allégée', 'Moutarde', 'Curcuma, cumin, curry en poudre', 'Cannelle', 'Herbes de Provence', 'Vinaigre balsamique', 'Pâte de curry jaune', 'Lait de coco light (1 boîte)', 'Bouillon de légumes (cube ou liquide)', 'Cacao pur non sucré'] },
  { cat: 'Boissons 💧', items: ['Eau plate (pack 6L)', 'Eau pétillante nature (pack)', 'Thé vert (boîte 25 sachets)', 'Infusions variées (camomille, menthe, gingembre)', 'Café en grains ou moulu'] },
  { cat: 'Snacks utiles 🥜', items: ['Noix (200g)', 'Amandes (200g)', 'Graines de chia (200g)', 'Chocolat noir 70% (100g)', 'Beurre amande (1 pot)', 'Graines de sésame (100g)', 'Muesli sans sucre (300g)'] },
];

export const SPORT_TIPS = [
  {
    icon: '💪', title: 'Renforcement musculaire',
    desc: '2 à 3 séances par semaine. Le muscle brûle des calories au repos et préserve votre métabolisme en période de déficit.',
    detail: {
      intro: 'Le renforcement musculaire est le pilier numéro 1 pendant une sèche. Sans lui, vous risquez de perdre autant de muscle que de gras.',
      points: [
        'Fréquence : 2 à 3 séances par semaine, non consécutives.',
        'Durée : 30 à 45 minutes par séance.',
        'Exercices : squats, fentes, pompes, rowing, développé épaules, gainage.',
        'Progressivité : augmentez la charge ou les répétitions chaque semaine.',
        'Matériel : haltères légers ou poids du corps suffisent pour commencer.',
        'Récupération : laissez 48h entre deux séances du même groupe musculaire.',
      ],
      example: 'Exemple de séance 30 min : Échauffement 5 min → Squats 3x12 → Pompes 3x10 → Fentes 3x10/jambe → Rowing haltères 3x12 → Gainage 3x30s → Étirements 5 min.',
      tip: 'Un muscle préservé = un métabolisme actif. C\'est votre meilleur allié pour ne pas reprendre le poids perdu.',
    },
  },
  {
    icon: '🚶', title: 'Marche quotidienne',
    desc: "Objectif 7 000 à 10 000 pas/jour. La marche est sous-estimée : c'est le cardio le plus durable sur le long terme.",
    detail: {
      intro: 'La marche est souvent négligée au profit du sport intense. Pourtant, elle représente la dépense énergétique la plus facile à maintenir sur le long terme.',
      points: [
        'Objectif : 7 000 à 10 000 pas par jour.',
        'Ne pas attendre de "trouver le temps" : intégrez la marche à votre routine (transports, courses, pause déjeuner).',
        'Marche post-repas (15-20 min) : réduit le pic glycémique et les envies de sucre.',
        'Utilisez un podomètre ou votre téléphone pour suivre vos pas.',
        'Si votre métier est sédentaire : levez-vous toutes les heures.',
        'Randonnée ou marche nature le week-end : excellent pour le moral et la dépense.',
      ],
      example: 'Exemple de journée active : 10 min à pied pour aller au travail + 20 min de marche le midi + 15 min post-dîner = déjà 45 min de marche.',
      tip: '10 000 pas représentent environ 300-400 kcal dépensées. Sur une semaine, c\'est l\'équivalent d\'une séance de sport intense.',
    },
  },
  {
    icon: '🚴', title: 'Cardio léger optionnel',
    desc: "Vélo, natation, elliptique : 1 à 2 séances de 30-40 min/semaine. Pas d'intensité excessive pour ne pas creuser trop le déficit.",
    detail: {
      intro: 'Le cardio léger complète bien le renforcement musculaire. Il améliore la condition cardiovasculaire et accélère la perte de gras — sans excès.',
      points: [
        'Activités idéales : vélo, natation, elliptique, footing lent, step.',
        'Intensité modérée : vous devez pouvoir tenir une conversation.',
        '1 à 2 séances de 30 à 40 minutes par semaine.',
        'Ne pas faire de cardio intense tous les jours : le corps ne récupère pas et le cortisol monte.',
        'Meilleur moment : matin à jeun (si vous le supportez) ou après une séance de renforcement.',
        'Ne pas compenser en mangeant plus après le cardio.',
      ],
      example: 'Exemple de semaine : Lundi renforcement, Mercredi vélo 35 min, Vendredi renforcement, Samedi marche nature.',
      tip: 'Le cardio brûle des calories SUR LE MOMENT. Le renforcement brûle des calories TOUT LE TEMPS. Les deux ensemble = résultats optimaux.',
    },
  },
  {
    icon: '😴', title: 'Priorité au sommeil',
    desc: "Le sommeil est le meilleur des récupérateurs. En manque de sommeil, la ghréline (hormone de la faim) augmente. Visez 7-9h par nuit.",
    detail: {
      intro: 'Le sommeil est souvent le facteur oublié de la perte de poids. Pourtant, il régule directement les hormones de la faim et de la satiété.',
      points: [
        'Ghréline (hormone de la faim) : augmente avec le manque de sommeil.',
        'Leptine (hormone de satiété) : diminue avec le manque de sommeil.',
        'Dormir moins de 6h = 24% de calories supplémentaires consommées en moyenne.',
        'Le muscle se construit et se répare pendant le sommeil profond.',
        'Évitez les écrans 1h avant de dormir (lumière bleue = perturbation mélatonine).',
        'Routine de coucher fixe (même heure de lever le week-end) = meilleure qualité de sommeil.',
        'Chambre fraîche (18-19°C), obscure et calme = conditions optimales.',
      ],
      example: 'Rituel du soir : infusion camomille → lecture 20 min → obscurité totale → même heure chaque jour.',
      tip: '7 à 9 heures de sommeil par nuit est aussi important que la nutrition pour perdre du gras durablement.',
    },
  },
  {
    icon: '⚖️', title: 'Ne pas compenser',
    desc: "Évitez de manger plus après le sport sous prétexte que vous avez \"brûlé des calories\". Estimez sobrement votre dépense réelle.",
    detail: {
      intro: 'La "compensation alimentaire" est l\'une des erreurs les plus courantes : on surestime ce que le sport a brûlé et on mange plus en conséquence.',
      points: [
        '30 min de vélo = environ 200-250 kcal brûlées. Pas autant qu\'on le croit.',
        'Une collation post-sport est utile UNIQUEMENT si vous avez fait plus d\'1h de sport intense.',
        'Si vous avez faim après une séance courte : buvez d\'abord de l\'eau, attendez 15 min.',
        'La collation post-sport idéale (si nécessaire) : 1 yaourt grec + 1 fruit = 200 kcal maximum.',
        'Évitez les barres protéinées industrielles souvent trop sucrées.',
        'Votre appétit augmente avec l\'intensité du sport — gérez-le avec des aliments rassasiants.',
      ],
      example: 'Exemple fréquent : séance de 30 min de jogging (200 kcal) puis repas supplémentaire de 500 kcal = bilan négatif pour la perte de poids.',
      tip: 'La perte de poids se fait à 80% dans l\'assiette et à 20% dans le sport. Concentrez-vous sur les deux, sans surestimer aucun.',
    },
  },
];

export const DRINKS = [
  { name: 'Eau plate', icon: '💧', rec: 'Minimum 1,5 L/jour, objectif 2 L', ok: true, detail: "L'eau est la boisson numéro 1. Elle régule la température corporelle, transporte les nutriments, élimine les déchets. Boire suffisamment améliore l'énergie, la concentration et réduit les fausses fringales (souvent confondues avec la soif). Astuce : posez une bouteille de 1,5L visible sur votre bureau." },
  { name: 'Thé vert', icon: '🍵', rec: '2 à 3 tasses par jour (antioxydant)', ok: true, detail: 'Le thé vert contient de la caféine et des catéchines (EGCG) qui légèrement stimulent le métabolisme. Il est riche en antioxydants. Évitez de le boire avec les repas (peut réduire absorption du fer). Idéal en milieu de matinée ou après-midi.' },
  { name: 'Café', icon: '☕', rec: 'Maximum 3 tasses/jour, sans sucre', ok: true, detail: 'Le café avant le sport améliore les performances et la mobilisation des graisses. Sans sucre, il est quasi acalorique. Évitez après 14h pour ne pas perturber le sommeil. Attention aux boissons café avec sirop ou chantilly (200+ kcal !).' },
  { name: 'Eau pétillante', icon: '🫧', rec: 'Sans sucre, peut aider contre les envies', ok: true, detail: "L'eau pétillante nature (0 calorie) est une excellente alternative pour ceux qui s'ennuient avec l'eau plate. Elle peut aider à réduire les envies de sodas. Ajoutez un filet de citron pour plus de saveur. Attention à l'acidité sur le long terme pour l'émail dentaire." },
  { name: 'Infusions', icon: '🌿', rec: 'À volonté, sans sucre', ok: true, detail: 'Les infusions (camomille, menthe, gingembre, verveine) sont excellentes le soir. Elles aident à se détendre, à réduire les envies sucrées nocturnes et à améliorer le sommeil. La menthe poivrée peut réduire la faim. Le gingembre est anti-inflammatoire.' },
  { name: 'Sodas / jus industriels', icon: '🚫', rec: 'À éviter : sucres cachés, index glycémique élevé', ok: false, detail: "Un verre de jus d'orange = 20g de sucre (l'équivalent de 5 morceaux). Un soda = 35g de sucre/canette. Ces boissons n'apportent aucune satiété et créent des pics glycémiques qui provoquent des fringales. Remplacez progressivement par de l'eau aromatisée maison." },
  { name: 'Boissons light', icon: '⚠️', rec: "Occasionnelles seulement, ne remplacent pas l'eau", ok: null, detail: "Les boissons light sont caloriquement neutres, mais les édulcorants entretiennent la dépendance au goût sucré. Des études suggèrent qu'ils peuvent perturber le microbiote intestinal. Utilisez-les comme aide transitoire pour réduire les sodas sucrés, pas comme habitude permanente." },
];
